### ISSUE TITLE
Script to translate Relex2Logic rules into ImplicationLinks (enabling execution via Atomspace-based rule engine)

### ISSUE THREAD

**Issue by AmeBel** [opencog/opencog#1193]
Currently the RelEx2Logic rules exist in a mixed format: there are “main rules” executed via a custom Java rule engine embedded in a RelEx output generator, assisted by “helper functions” written in Scheme and interacting directly with the Atomspace.

We would like to eliminate the use of the custom Java rule engine and have each RelEx2Logic rule executed via triggering an ImplicationLink (wrapped in a BindLink) in the AtomSpace. This involves wrapping the helper functions in GroundedSchemaNodes, and writing a script to map the main RelEx2Logic rules into ImplicationLinks among Atoms. In principle this is straightforward but various fixes and tweaks to various AtomSpace related functions will likely be required along the way.

* check https://github.com/opencog/opencog/issues/1208 for discussion on the rule syntax

[ ] handle issue raised @ https://github.com/opencog/opencog/pull/1136#discussion_r24643058

**Comment by AmeBel** [comment]
@anitzkin what is your design improvement suggestions with regards to the r2l porting to URE.

**Comment by anitzkin** [comment]
Hm.  Haven't thought a lot about this yet -- been working on two other
projects -- so I'm sure that I will have much more to say on the
subject as soon as I start looking at the details . .. but, as regards
previous discussions, I lean strongly towards (1) abandoning priorities,
(2) using disjunct sets when necessary, (3) obviating the need for
elaborate disjunct-sets in general by (a) getting better relex output and
(b) making the r2l rules more modular--as in having R2l rules apply in
general, to specific dependency relations rather than entire sentence
structures--although in some cases, I think that will be done within the
context of branching conditional functions, like I already installed in the
scheme helpers for differentiating certain sets of sentence structures and
question types.  But in general, I think it best to think in terms of
individual relations rather than writing rules for sets of relations.  You
get more flexibility and more coverage.  I really don't think we should
need to use a priority, or cost-system, much, perhaps not at all, if the
relex output were good enough.  However, I've run up against the wall of LG
in my relex revisions; I have a small back-log of relex errors that I hope
can be fixed by revising the LG dictionary and a short-list of things that
would probably require revisions to either the LG or Relex code; I've
spoken to Ben about some of this . . . Some things, such as the logic of
individual prepositions, is not resolvable within R2l alone; their
semantics require the application of general intelligence, at least in the
form of PLN + knowledge-base.  So, I will also recomend leaving some
aspects of relational logic un-resolved in R2L because they depend on
lexical semantics or pragmatics.  Most of what I've said here I've already
implemented to some degree.  And just as an aside, keep in mind that there
are lots of completely new R2L rules waiting to be written, based on my
recent revisions of relex . . .

There, you got me wroking on Opencog after hours, you bastard.

--Aaron

**Comment by AmeBel** [comment]
what is TruthValueGreaterThanLink @ https://github.com/opencog/opencog/blob/master/opencog/nlp/relex2logic/rule-helpers.scm#L1245 ?

**Comment by linas** [comment]
Closed because its done!
