### ISSUE TITLE
Import of opendial rules into opencog based system

### ISSUE THREAD

**Issue by AmeBel** [opencog/opencog#1201]
The OpenDial chatbot, utilizing a combination of hand-coded rules and calls to external systems, displays a reasonably powerful chat functionality. This functionality can be ported into the OpenCog dialogue system, giving the OpenCog dialogue system the ability to conduct reasonably interesting conversations.

A script can be written to translate OpenDial rules (which are expressed as implications) into OpenCog ImplicationLink; and it should be straightforward to translate OpenDial references to external sources (like MegaHal and OpenEphyra) into GroundedSchemaNodes referenceable within OpenCog ImplicationLinks. However, some thinking will need to be done regarding how to break up the OpenDial functionality among speech act schema. Some of the OpenDial functionality may go into new speech act schema (e.g. a “say something amusing” schema wrapping up the MegaHal reference), and some may be wrapped into existing speech act schema (e.g. the OpenEphyra reference could be invoked by the general question-answering schema, to be utilized when no sufficiently good answer to the question at hand is found within the Atomspace directly). The AIML-type rules used within OpenDial may end up being divided among various existing speech act schema (e.g. OpenDial rules for greetings could be placed within a general greetings schema).

OpenDial handling of dialogue variables (e.g. the user’s name) will have to be mapped into OpenCog structures carefully and probably on a case-by-case basis.

**Comment by linas** [comment]
Why exactly is this an useful or interesting thing to do?

Based on prior experience, this does not sound like a good idea to me -- in fact, its a terrible one. My experience: about 9 years ago now, before I got into opencog I tried to build a question-answering system that could answer questions (it sort-of-worked) and then backfill the rest of the conversation with AIML, so that it could chat whenever it did not have an suitable answer.  It sounded like a great idea, but proved to be horrible.

One of the major problems was in carving out the parts that I wanted to handle in the QA system, vs. what the chatbot could respond to. It was just rather infeasible, and I'm not convinced its feasible today, not without some major design and architecture work to figure out how to do it right ...

**Comment by linas** [comment]
Upshot: I don't think this is a good idea ...

**Comment by githart** [comment]
I agree with Linas on this one based on my own previous experience with a 'hybrid' chat system where one subsystem would backfill conversation when another was stuck, it was a disaster. Better to put in the design and architecture effort to 'figure out how to do it right' as Linas says.

**Comment by linas** [comment]
FYI, the OpenDial rules could be imported, if desired, uusing a system similar to that in https://github.com/opencog/opencog/tree/master/opencog/nlp/aiml

**Comment by linas** [comment]
Closing, this is a stale plan.
