### ISSUE TITLE
Memory leak in PatternMatchEngine::note_root

### ISSUE THREAD

**Issue by ngeiswei** [opencog/opencog#1211]
I think there is a memory leak in PatternMatchEngine::note_root, l.893 in PatternMatcherEngine.cc
```
        rl = new RootList();
```
Although _root_map is cleared in PatternMatchEngine::clear() the mapped vectors are never cleared.

**Comment by ngeiswei** [comment]
I've commited a fix https://github.com/ngeiswei/opencog/commit/1c2ddb68f0024003014fb79ec45ac0a7ea88736a on my branch https://github.com/ngeiswei/opencog/tree/pattern-matcher-improvements-or-so-it-says

**Comment by linas** [comment]
I looked at the changes. I mostly surmise that you are reading very carefully. I hope you are understanding most of it. 

Much of it is fairly straightforward, but there are some really confusing bits to it. So for example, unordered links are not really fully/correctly supported, see bug #1091 . Its confusing because for unordered links, you have to try every permutation ... which isn't bad, except that these things nest.  Which complicates stuff. And then even if you find a match or one permutation, you still have to try all the others. It makes my head spin, when I try to implement it ... and I think that, what that really means is that somehow, the code is not as clearly/cleanly structured as it could be.   Because its somehow obvious what to do, but not obvious on how to code it...

**Comment by linas** [comment]
Re: the mem leak, yes very possible. I think I might have added that recently, and, during the coding jag, just forgot to delete. 

The unit tests are really pretty extensive and authoritative: if you change something, and the unit tests still pass, then its a valid change.

**Comment by linas** [comment]
Just do a pull request when you are ready.

**Comment by ngeiswei** [comment]
Linas, I've done the pull request, I think it's OK enough that I could merge myself but just in case I let it to you for this time.

**Comment by linas** [comment]
This was fixed in pull #1221 right?

**Comment by ngeiswei** [comment]
Indeed.
