### ISSUE TITLE
Add some basic combo vocabulary definition

### ISSUE THREAD

**Issue by ngeiswei** [opencog/opencog#1317]
# Motivation

The combo language is expandable with actions perceptions primitives, but so far there is no basic definition that one can use for writing just arithmetic or boolean expression but nothing else (i.e. without primitives for actions and perceptions). So far we've used

```
opencog/comboreduct/ant_combo_vocabulary/ant_combo_vocabulary.h
```

which is

basic combo + some action/perception primitives for the Santa Fe Trail problem https://en.wikipedia.org/wiki/Santa_Fe_Trail_problem

This definition is used all over the code, as for instance in

```
tests/comboreduct/reduct/BooleanReductUTest.cxxtest
```

This is kinda a dumb and confusing to have to use the Santa Fe Trail problem combo extension when all that one wants to do is boolean algebra.

# Task

So the task would be to add beside 

```
opencog/opencog/comboreduct/ant_combo_vocabulary
```

a folder

```
opencog/opencog/comboreduct/basic_combo_vocabulary
```

that contains a version of stripped down version of ant_combo_vocabulary without the ant actions and perceptions.

Then once this stripped down version is coded, whenever possible, includes such as

```
#include <opencog/comboreduct/ant_combo_vocabulary/ant_combo_vocabulary.h>
```

in

```
tests/comboreduct/reduct/BooleanReductUTest.cxxtest
```

should be replaced by the stripped down version, that is

```
#include <opencog/comboreduct/basic_combo_vocabulary/basic_combo_vocabulary.h>
```

don't forget to replace the namespace as well, that is

```
using namespace ant_combo;
```

by

```
using namespace basic_combo;
```

**Comment by linas** [comment]
I don't think that you need a basic_combo_vocabulary.h because .. if you remove all the ant stuff, all that is left is `#include <opencog/comboreduct/combo/combo.h>`  which most files include already.

The problem is that if you change other code to not include ant_combo_vocabulary.h then somewhere along the way, things stop compiling and/or stop working.  As a result, ant_combo_vocabulary.h is "invasive" -- everything needs it, but almost nothing uses it.

The real solution would be to invent some kind of extension mechanism, so that if something doesn't use ant, it doesn't need it to compile and link.

**Comment by linas** [comment]
Here: I just pushed two commits that removed most uses of ant_combo_vocabulary.h from the unit tests.  However, the CMakfiles still require comboant to link, and if you try to remove that, then you get an error message:
```
../../../opencog/comboreduct/libcomboreduct.so: undefined reference to `opencog::combo::operator>>(std::istream&, opencog::tree<boost::variant<double, opencog::combo::enum_t, opencog::combo::id::builtin, opencog::combo::id::wild_card, opencog::combo::argument, opencog::combo::id::action, opencog::combo::builtin_action_base const*, opencog::combo::perception_bas ...
```
Right? and that is because the ant stuff shows up in the vertex boost variant, at compile time.

What we really need is a boost::variant that can be extended at runtime, not compile time .. or maybe be extended at compile time, so that only some files get the extra ant stuff in the variant, but not all.

Having a boost variant like this would also allow opencog atomspace atoms to be shoved in there, something that is impossible today.

The other possibility is to redesign the vertex so that it doent use variant, but this would be a huge task.

**Comment by ngeiswei** [comment]
Linas,

I've added this issue for Devansh (I thought it was so not high priority that nobody would care).

As you can see it doesn't compile, because it requires the operator>> to be defined. For that you need to pass to stream_to_vertex some dummy action perception.

Maybe there are other things but I'm not sure.

Anyway, as you can see that it's not merely including combo.h rather than ant_combo_vocabulary.h, for you or I it's rather trivial, but for Devansh, it's a good exercise.

**Comment by ngeiswei** [comment]
Ideally I would prefer if you revert your changes, since they are not working anyway.

**Comment by ngeiswei** [comment]
Hmm, I guess maybe you can just add this operator>> overload in combo_io.h, instead of the basic_combo_vocabulary I suggest. But it would have to have a special namespace as to not collapse again the over operator>> overloads of the other combo vocabulary definitions, like avatar_combo_vocabulary in embodiment.

Linas, I agree with you it would be better if all those extensions are loaded at run-time, but that's too big for such an exercise.

**Comment by ngeiswei** [comment]
Hmm, it all compiles, meaning what you've done seems correct, I don't get it, I'll have a closer look at your changes...

**Comment by ngeiswei** [comment]
I get it, it uses

```
std::istream& operator>>(std::istream& in, combo::vertex& v);
```

from util/tree.h

I just don't understand why I used the ant version then. Although I'm not so sure then how the ant combo vocabulary (or the avatar combo vocabulary) plays with that. It seems the action perception reduct utests are disabled, so I can't check right away. Anyway, I'll look into this more deeply tomorrow.

**Comment by ngeiswei** [comment]
Ahah! Of course, as you say it does rely on the operator>> defined in ant_combo_vocabulary.cc! The version of operator>> declared in vertex.h actually points to it!!! Not the implementation in tree.h (I think due to the fact that it's not in the combo namespace).

So really it's still the good old (or bad should I say) ant version of operator>> just hidden below the surface...

There must be a clearer way... Anyway maybe it's really time to move all this at run-time.

BTW, some the action perception types (like action arguments) could be simplified, and definite object could be enum, or such. This whole think must rethought and cleaned up. But again it's too big for a small student exercise.

**Comment by linas** [comment]
Sorry Nil,

Didn't know. Just say: For Devanah" .. and there is also an "Assignee" on the bottom of right side column -- you can fill that out.   Its just that I was thinking about moses again yesterday, and saw this this morning so I just did it.

**Comment by linas** [comment]
moses code has moved, I've created issue opencog/moses#39 to continue tracking this.
