### ISSUE TITLE
ExecutionOutputLink cannot be nested

### ISSUE THREAD

**Issue by linas** [opencog/opencog#1340]
ExecuationOutputLink needs to be nestable, so that, for example, something similar to the following works:
```
ExecutionOutputLink
    "scm: +"
    ListLink
         ExecutionOutputLink
              "scm: *"
              ListLink
                  NumberNode 1
                  NumberNode 2
         NumberNode 3
```
is a representation of 1*2 + 3

**Comment by inflector** [comment]
We also have the problem that Python's interface is currently to a function that takes arguments and returns an atom. So `*` is not going to work.

You could define a function that added, however, something like: `add_nodes` but you would currently have to also return a NumberNode atom containing the 3, not the number `3` as in your example because the ExecutionOutputLink is expecting a atom returned from the python function it calls.

**Comment by linas** [comment]
This has nothing at all to do with python.  This is an issue with the current design of the grounded predicate nodes, and grounded schema nodes.

**Comment by linas** [comment]
The test case for this is in `./tests/scm/SCMExecutionOutputUTest` in the last bit, the "nested test"
