### ISSUE TITLE
Avoid or minimize passing of AtomSpace* into evaluation and execution links.

### ISSUE THREAD

**Issue by inflector** [opencog/opencog#1370]
> fwiw python_eval should also take atomspace as an argument somewhere, so that it acts on the correct atomspace. - @linas in #1319
1. Pass the atomspace into the `PythonEval::eval` and `PythonEval::eval_tv` 
2. Make sure the ATOMSPACE Python variable refers to the right atomspace
3. Swap back ATOMSPACE afterward so that it preserves server ATOMSPACE by default ???

Need to think about the implications of swapping back as this may be unnecessary. It might be only necessary to make sure that ATOMSPACE is set to the one passed in.

**Comment by linas** [comment]
Yeah, I decided that the way atomspaces are passed around is all borked (not just in python, but also in guile, and the whole evaluator/executor mechanism).  So really, this is not a python bug,  but an atomspace bug.

My plan is to eventually change things (when I get around to it) so that EvaluationLink and ExecutationLink use the same atomspace that the link itself is in.  Ditto for BindLink, SatisfactionLink.  I think this will clear up a lot of the atomsapce pointer-passing confusion.

Not all pointer-passing can be eliminated; exectuation of virtual links still has to happen in a temporary atomspace and not the main one...

**Comment by linas** [comment]
closing; stale bug report; that code base is not in this repo any longer.
