### ISSUE TITLE
cog-fc causes segfault

### ISSUE THREAD

**Issue by AmeBel** [opencog/opencog#1380]
Steps for reproducing the segfault, after removing all rules except the deduction rule in `default_cpolicy.json`

```
guile> (clear) (load-scm-from-file "../opencog/python/pln/examples/deduction/atomspace_contents.scm")
0
guile> (define a (list-ref (cog-get-atoms 'InheritanceLink) 0))
guile> (cog-fc a)
(ListLink
)
guile> (cog-fc a)

```

Below is the Stack Trace:
```
[2015-03-10 01:39:52:630] [ERROR] Caught signal 11 (Segmentation fault) on thread 139717857892096
        Stack Trace:
        2: ./opencog/server/cogserver (opencog::Logger::Base::~Base() +0x5e) [0x40813e]
        3: ./opencog/server/cogserver (sighand(int) +0xe9) [0x407779]
        4: /lib/x86_64-linux-gnu/libc.so.6 ( +0x36d40) [0x7f12ae480d40]
        5: /home/opencog/build/opencog/atomspace/libatomspace.so (opencog::NodeIndex::getHandle(unsigned short, char const*) const +0x13) [0x7f12ae208993]
        6: /home/opencog/build/opencog/atomspace/libatomspace.so (opencog::AtomTable::getHandle(unsigned short, std::string const&) const +0x50) [0x7f12ae1d9780]
        7: /home/opencog/build/opencog/atomspace/libatomspace.so (opencog::AtomSpaceImpl::addNode(unsigned short, std::string const&, bool) +0x2e) [0x7f12ae1cfc9e]
        8: /home/opencog/build/opencog/reasoning/RuleEngine/rule-engine-src/libruleengine.so (DefaultForwardChainerCB::target_to_pmimplicant(opencog::Handle, std::map<opencog::Handle, std::string, std::less<op
encog::Handle>, std::allocator<std::pair<opencog::Handle const, std::string> > >) +0x54f) [0x7f129b649b8f]
        9: /home/opencog/build/opencog/reasoning/RuleEngine/rule-engine-src/libruleengine.so (DefaultForwardChainerCB::target_to_pmimplicant(opencog::Handle, std::map<opencog::Handle, std::string, std::less<op
encog::Handle>, std::allocator<std::pair<opencog::Handle const, std::string> > >) +0x2a4) [0x7f129b6498e4]
        10: /home/opencog/build/opencog/reasoning/RuleEngine/rule-engine-src/libruleengine.so (DefaultForwardChainerCB::choose_input(FCMemory&) +0x2e8) [0x7f129b64adc8]
        11: /home/opencog/build/opencog/reasoning/RuleEngine/rule-engine-src/libruleengine.so (ForwardChainer::do_chain(ForwardChainerCallBack&, opencog::Handle) +0x11e) [0x7f129b644cfe]
        12: /home/opencog/build/opencog/reasoning/RuleEngine/rule-engine-src/libruleengine.so (opencog::InferenceSCM::do_forward_chaining(opencog::Handle) +0xc9) [0x7f129b650c29]
        13: /home/opencog/build/opencog/reasoning/RuleEngine/rule-engine-src/libruleengine.so (opencog::SchemePrimitive<opencog::InferenceSCM>::invoke(scm_unused_struct*) +0x12ad) [0x7f129b65214d]
        14: /home/opencog/build/opencog/guile/libsmob.so (opencog::PrimitiveEnviron::do_call(scm_unused_struct*, scm_unused_struct*) +0x24) [0x7f12ad943814]
        15: /usr/lib/libguile-2.0.so.22 ( +0xecc00) [0x7f12aba25c00]
        16: /usr/lib/libguile-2.0.so.22 ( +0x27) [0x7f12ab99d747]
        17: /usr/lib/libguile-2.0.so.22 ( +0xecc00) [0x7f12aba25c00]
        18: /usr/lib/libguile-2.0.so.22 ( +0x2e) [0x7f12ab99d81e]
        19: /usr/lib/libguile-2.0.so.22 ( +0xecc00) [0x7f12aba25c00]
        20: /usr/lib/libguile-2.0.so.22 ( +0x33) [0x7f12ab99d863]
        21: /home/opencog/build/opencog/guile/libsmob.so (opencog::SchemeEval::do_eval(std::string const&) +0x94) [0x7f12ad93ffa4]
        22: /home/opencog/build/opencog/guile/libsmob.so (opencog::SchemeEval::c_wrap_eval(void*) +0x33) [0x7f12ad9400c3]
        23: /usr/lib/libguile-2.0.so.22 ( +0x5b2ca) [0x7f12ab9942ca]
        24: /usr/lib/libguile-2.0.so.22 ( +0xecc00) [0x7f12aba25c00]
        25: /usr/lib/libguile-2.0.so.22 ( +0x33) [0x7f12ab99d863]
        26: /usr/lib/libguile-2.0.so.22 ( +0x5b9ff) [0x7f12ab9949ff]
        27: /usr/lib/libguile-2.0.so.22 ( +0x35) [0x7f12ab994a95]
        28: /usr/lib/libguile-2.0.so.22 ( +0xd478c) [0x7f12aba0d78c]
        29: /usr/lib/x86_64-linux-gnu/libgc.so.1 ( +0x12) [0x7f12aa717fe2]
        30: /usr/lib/libguile-2.0.so.22 ( +0x28) [0x7f12aba0db48]
        31: /home/opencog/build/opencog/guile/libsmob.so (opencog::SchemeEval::eval_expr(std::string const&) +0x2e) [0x7f12ad94006e]
        32: /home/opencog/build/opencog/shell/libscheme-shell.so ( +0x7ba7) [0x7f129f99bba7]
        33: /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb1bf0) [0x7f12aead6bf0]
        34: /lib/x86_64-linux-gnu/libpthread.so.0 ( +0x8182) [0x7f12ad50a182]
        35: /lib/x86_64-linux-gnu/libc.so.6 ( +0x6d) [0x7f12ae54447d]
```

**Comment by misgeatgit** [comment]
I will take a look at it.Its related with the recent refactoring and changes I introduced.Will finish the integration work on it.

**Comment by AmeBel** [comment]
ok thanks. In `(cog-fc a)` a is
```  
   (InheritanceLink (stv 0.89999998 0.111111)
   (ConceptNode "Animal" (stv 0.1 0.111111))
   (PredicateNode "Moves" (stv 0.1 0.111111)))
```

**Comment by williampma** [comment]
The same crash happens when instead of doing `(cog-fc a)` the second time, do `(cog-prt-atomspace)` instead.  So I guess it is something the first `(cog-fc a)` did that corrupted the atomspace.

**Comment by misgeatgit** [comment]
OK, I have just started debugging this situation.

**Comment by linas** [comment]
Hmm. It should be impossible to core-dump the atomspace by doing "normal" things.

**Comment by linas** [comment]
hey, if you install libiberty and Binutils, then you'll get a stack trace with line numbers in it.  That is easier to debug ...

**Comment by misgeatgit** [comment]
@linas  Thanks for the tip.

**Comment by linas** [comment]
Hmm bugs like this make me nervous.  Make sure that the atomspace pointer is not NULL when the crash occurs. Make sure the atomspace has not been deleted (and the atomspace pointer is pointing to the deleted atomspace).  Either of these would cause a crashy NodeIndex.  (add a print statement to atomspace::delete().

I mention this because some of the recent python work, and also a re-org of the scheme code caused multiple atomspaces to be created and destroyed at the wrong times.  Make sure you can reproduce on a recent pull (no more than a week old).

**Comment by linas** [comment]
Also: if you use GroundedPredicateNode's in PLN, then be aware that the pattern matcher uses a temporary atomspace to hold temporary results; that atomspace is then deleted. It seems very unlikely that this atomspace could "leak" out into your code ... but hey, anything can happen.

**Comment by misgeatgit** [comment]
Changed the way rule_atomspace is created 5fb523b11d4cc6a346ac03191 to be dynamically and the crash doesn't appear any more.

**Comment by williampma** [comment]
Maybe because you are not deleting it, so that dangling memory is available outside the function...

Looks dangerous...?

**Comment by misgeatgit** [comment]
Yes I closed my PR for that reason. Thanks.

**Comment by misgeatgit** [comment]
>Maybe because you are not deleting it, so that dangling memory is available outside the function...
>Looks dangerous...?

Yes, The crash is happening when the temporary independent atomspace(http://wiki.opencog.org/w/Multiple_atom_spaces#Independent_AtomSpaces) It seems I didn't misuse anything there.

**Comment by linas** [comment]
It is possible that this commit b9057dcbe5f27d3deaf82a54f8a14077caa89a24  might fix this bug...

Recall: atoms continue to exist, as long as there is some handle, somewhere, that continues to point to it.   So, when deleting an atomspace, that atoms will continue to exist, as long as there are handles point at them.  The above commit just makes sure that they are no longer pointing at a dead atomspace.

**Comment by williampma** [comment]
Unfortunately, that didn't fix it.  It's still crashing at `(cog-prt-atomspace)`

**Comment by williampma** [comment]
@misgeatgit Not a fix (since I did not identify the problem), but for some reason while I was fooling around the code and changed it to stop using SchemeEval to add handles to different atomspace, the crash does not happen (see https://github.com/williampma/opencog/commit/0cdfdcaaf86aa2121a7fc5e8dc702ee3f1d31913)

Maybe it is just random chance, or maybe SchemeEval also has something to do with it.

**Comment by misgeatgit** [comment]
@williampma  that seems to solve the problem even if it doesn't explain the bug. AddAtom seems the better way performance wise. Can you make a PR? or whats your suggestion?

**Comment by williampma** [comment]
I think it is better to identify the bug :)  The above "fix" might just be random chances and the bug could creep up in other unexpected places.

**Comment by williampma** [comment]
I wonder if the code is tripping over this XXX FIXME https://github.com/opencog/opencog/blob/master/opencog/guile/SchemeEval.cc#L279-L286

Maybe, maybe not.

**Comment by linas** [comment]
argh. I just pushed a change that I thought might help, but in fact, it might make the problem worse.  You guys are doing wilder and crazier things with atomspaces and guile than I ever thought anyone would do.

I really doubt that SchemeEval.cc#L279-L286 has naything do do with this problem: it has all of teh symptoms of crashing due to an access to a non-existent atomspace.  I'm digging through your code now ...

**Comment by linas** [comment]
I'm looking at the code now. In one place, you are using scheme eval to simply copy atoms from one atsompace to another.You do not need to use scheme val at all for this.  You can just copy the atoms, at will.

**Comment by linas** [comment]
Also, the unit tests are broken: running `./tests/reasoning/RuleEngine/JsonicControlPolicyParamLoaderUTest ` from the command line causes it to fail, but running it from the test harness causes it to pass. That's bad -- it makes the thing hard to debug.

**Comment by linas** [comment]
basically, the json file cannot be found .. which is why the unit tests are failing

**Comment by linas** [comment]
I'm not sure, but I think that pull request #1405 might also fix this problem, or make it easier to find.  I ws unable to make forward progress, because the json files are not being loaded, and I could not figure out how that json code worked.

**Comment by linas** [comment]
Anyway, please review the changes to lines  54, 62 and 96 of
opencog/reasoning/RuleEngine/rule-engine-src/pln/DefaultForwardChainerCB.cc in pull request #1405 -- I think this is what you are trying to do: to copy atoms from one atomspace to another.  However, it is difficult to tell what is really going on here, because the atomspace usage is confusing to me.

It looks to me like you are trying to use a deleted atomspace. One way that this might be happening is that if you perform the following steps:
1) create an atomspace
2) tell scheme to use that atomspace by default
3) delete that atomspace
4) use scheme, without specifying a new default atomspace.

That is one way tto get a use-after-free. I cannot tell if this is what is actually happening here. If it is, then the correct long-term fix is probably to write some sort of notifier code that lets scheme know when it's default atomspace has been deleted.  In the meantime, you may need to make sure you are not doing step2) on purpose, or by accident.

**Comment by linas** [comment]
OK, so pull request #1430 should really fix it, this time.   The actual fix was here: fc31a4b24e6a3b35dacebaf7865c90c261283581  and the unit test that tests this fix is here:  11ef7f927d8f14ebb34cb4f8d8913f0ff9de1342  Notice how the atomspace copies an atom from one atomspace to another, and back again. The copying now works as it was supposed to all along :-)

I also removed the usage of SchemeEval here: dc04c1dfb2aeca2d7933bb19a446dd058d51db5d because it really is no longer needed.

**Comment by misgeatgit** [comment]
Thanks.

**Comment by AmeBel** [comment]
Thanks
