### ISSUE TITLE
Piping a lot of scheme code consumes a lot of RAM

### ISSUE THREAD

**Issue by ngeiswei** [opencog/opencog#1419]
When piping large scheme files (> 30MB) the RAM consumption goes crazy high > 8GB.

As a work around I can set do_async_output to false in method SchemeShell::SchemeShell, then the RAM remains quite low.

Do we need to add a config option SCM_ASYNC_OUTPUT to control that? Or does that require a real fix? Or is this already parameterizable in another way?

**Comment by linas** [comment]
Wow. I think there's a bug or buglet or mis-feature, you've stumbled onto a clue.  Behavior like this was previously noted in bug #1116 and I hacked around it by forcing garbage collection to run more often than the default in pull request #1117 -- however, that hurts performance.  And it seems hacky. 

Because calling garbage collection more often causes significantly less mem usage, that suggested that its not a true memleak, but rather that it is enlarging the heap, increasing the working set, and then promptly freeing all that memory.  But, if avoiding using threads can also avoid the problem... Hmm.

Understanding why this is happening is almost surely a difficult task.  So adding a flag for it, as a short-term work-around, makes sense.

**Comment by linas** [comment]
I just merged #1420 which adds a flag: so if you start your scheme shell with "scm sync" then you will get sync output.  

By the way, does the problem occur if you say "scm hush" ?  Because the hush flag suppresses output entirely, or rather, dumps it. If the problem goes away with "scm hush", that would narrow it down a lot...

**Comment by ngeiswei** [comment]
Linas, actually "scm hush" or "scm quiet" fixes it, but "scm sync" doesn't!

**Comment by ngeiswei** [comment]
Oh, "scm shit" actually fixes it as well ;-D there must be a problem with the way the argument of scm is parsed...

**Comment by ngeiswei** [comment]
OK, I've merged a fix, now "scm sync" fixes the issue, while "scm hush" doesn't. Which makes more sense.

**Comment by linas** [comment]
Closing, I think this fixed itself long ago.
