### ISSUE TITLE
Replace JSON PLN config file by YAML (SCHEME actually)

### ISSUE THREAD

**Issue by ngeiswei** [opencog/opencog#1462]
According to

http://stackoverflow.com/questions/244777/can-i-comment-a-json-file#244858

JSON does not have any easy way to add comments, that's a bit of a pain. It would be better to use YAML, or even OpenCog config file. What do you say?

**Comment by ngeiswei** [comment]
I mean the reason is that one typically wants to comment out a bunch of rules...

**Comment by misgeatgit** [comment]
I found opencog config unnatural for complicated grouping of set of attributes and their values.YAML is nice but we might need to introduce a new dependency library in opencog for YAML parsing.

**Comment by ngeiswei** [comment]
Makes sense, YAML would be cooler thought. I found yaml-cpp on my ubuntu repo, it looks like the standard way to handle YAML in C++.

Anyway, I guess it's not very important.

**Comment by linas** [comment]
I see no reason why the rules can't be written as scheme... scheme was originally intended to be a glorified config-file/markup language of opencog, and not really something to code in....

**Comment by williampma** [comment]
Since the RuleEngine will also be used for RelEx2Logic, not just PLN, whatever rule file it ended up with should also work with the more complicated usage.

It was discussed at length in https://github.com/opencog/opencog/issues/1208

**Comment by ngeiswei** [comment]
I'm coming to agree with Linas, why not use Scheme instead of JSON and have all the parameters loaded in the AtomSpace? Ultimately we want to have those parameters in the AtomSpace anyway as to enable finner level of control and meta-learning.

And this format at least allows to comment out parts of the config file!!! (JSON not supporting this is a good reason to stay away from it, IMO).

**Comment by ngeiswei** [comment]
Well, R2L config is apparently coded in Scheme

https://github.com/opencog/opencog/blob/master/opencog/reasoning/RuleEngine/r2l-en-rulebase.scm

and it predates the json file, so I can't understand why json was used instead of scheme...

**Comment by misgeatgit** [comment]
I never thought of using scheme for configuration purpose before because I have not used it much. I thought config fie was supposed to handle such things and when I tried to use it for my purpose it became complicated and I thought why not use Json since we already have its usage somewhere else inside the code base. I am still willing to do the necessary changes to move the rule declaration in to a scheme file.

**Comment by ngeiswei** [comment]
@misgeatgit thanks for offering, yeah it would be cool if you can port the json config file to scheme.

**Comment by misgeatgit** [comment]
But am still not sure how to do it. Particularly mapping of key values. Perhaps using ordered links?

**Comment by AmeBel** [comment]
you can use alists for maps
https://www.gnu.org/software/guile/manual/guile.html#Association-Lists

**Comment by misgeatgit** [comment]
I guess something like https://github.com/opencog/opencog/blob/master/opencog/reasoning/RuleEngine/r2l-en-rulebase.scm#L54 suffices.

**Comment by AmeBel** [comment]
@ngeiswei are you thinking of defining the rules and the categories within the atomspace as in https://github.com/opencog/opencog/blob/master/opencog/reasoning/RuleEngine/r2l-en-rulebase.scm or just porting https://github.com/opencog/opencog/blob/master/opencog/reasoning/RuleEngine/default_cpolicy.json to scheme format?

I guess having the categorization within the atomspace could help with meta-learing/backward-changing because it will help filter the BindLinks(rule-definitions) from BindLinks used for quering or other non-rule related purposes, right?. The port of the cpolicy to scheme might then just work with the rule-variable names (like pln-rule-deduction)

**Comment by AmeBel** [comment]
It may worth checking https://github.com/opencog/opencog/blob/master/examples/pattern-matcher/fsm-full.scm too.

**Comment by ngeiswei** [comment]
@AmeBel yes exactly with the categories.

**Comment by linas** [comment]
New URL's  are
https://github.com/opencog/opencog/blob/master/opencog/reasoning/r2l/rules/r2l-en-rulebase.scm
and

https://github.com/opencog/opencog/blob/master/opencog/reasoning/engine/default_cpolicy.json

**Comment by linas** [comment]
I would like to see default_cpolicy.json ported to the atomspace.  Hre is a wild guess for the format:

```
(ContextLink  (stv 1 1) ;; the truth value is "priority" in the json file
    (ConceptNode "PLN")   ;; this is the "category" from json file
    (ChoiceLink     ;; this is the "mutex" from the json file.
          (ConceptNode "pln-rule-deduction")  ;; this is "name" from json file
    )
)
```

The TV plays the role of "priority" from the json file, so that  lower priority == lower TV.

The ChoiceLink currently has only on entry each, because the json file currently does not list any mutually-exclusive rules. Otherwise, all mutexed rules would be listed in one ChoiceLink.

The TV on the rule could indicate the priority for that rule, as opposed to applying other rules.

"filepath" in json is not needed.

re priority: if you want to apply two rules, picking one half the time, and half-the time picking the other, then just say:  `(ContextLink (stv 0.5 1) ...)` for one rule, and `(ContextLink (stv 0.5 1) ...)` for the other rule.

If you want to always apply rules in a given order, so that rule 1 is always tried before rule 2, etc. then do this:

```
(SequentialAndLink
    (ContextLink ... rule 1 ...)
    (ContextLink ... rule 2 ...)
   ... etc ...
)
```

**Comment by AmeBel** [comment]
@linas if i am not mistaken the strength of the TV is playing the idea of cost you mentioned in another issue/thread (couldn't find it)? Something about link-grammar disjuncts

**Comment by linas** [comment]
Amen, yes.

I've been thinking about this, and am starting to think that perhaps,
if expressed correctly, the URE could become a built-in part of the
pattern matcher, or posibly some simple layer on top of it.  Here's
why I think this:

A recent change to the pattern matcher adds the ChoiceLink (I just
added this to the wiki) which says "match this or this or this".   Its
similar to what is going on here: "apply this rule or this rule or
this rule".

Another change I'm thinking about, but haven't done yet, is to
eliminate BlindLink entirely, and replace it with a combination of
SatisfactionLink and a new link type: RewriteLink, which would play
the role that Imp[licationLink does today in the pattern matcher. That
would help make it clear that the implicationLink is somehow different
than an ordinary implication link when it shows up inside the pattern
matcher.

There are also two changes, which I pushed to github earlier today.
First, you no longer have to declar varaibles with either BindLink or
SatisfactionLink.  If you don't declare variables, the PM will search
for all variables in the expression, and try to ground those.

The second change is that using SatsifactionLink is now completely
optional. Thus, you can just  give it any old link that has variables
in it, and it will find those variables, and then try to ground them.
It works now.

Thus, I could make BindLink completely optional too; if you don't
specify it, the pattern matcher ould just find all the variables in
it, and try to ground them.  However, its still a bit confusing: how
should ImplicationLinks be handled?  To eliminate this confusion, I'm
thinking of using the RewriteLink.

If BindLink  is completely optional, and the pattern matcher "just
works anyway", then maybe a list of rules could be handled almost
automatically, too, simply by nesting them in a ChoiceLink
appropriately.  Or something like that. Or maybe they might work like
the finite-state-machine, as you pointed out.  Not sure.  I haven't
quite figured out all the details that would make this "easy" and
"natural".

Oh by they way: there is yet another change that was strengthened/made
more clear in the last few weeks:  When you include GPN's (not GSN's)
in the body of a pattern, they accept or reject a pattern. You already
know about EqualLink and AbsentLink; there  is also GreaterThanLink.
These, and GPN's in general, can be combined with AndLink, OrLink and
NotLink to create arbitrary boolean expressions that accept or reject
a pattern.

I'm thinking of inventing a "MustBePresentLink", the opposite of an
AbsentLink, that would also be trut-valued. Thus, if the pattern
matcher can ground a MustBePresentLink, then it evaluates to true.
Since its boolean, it can be combined with AndLink, OrLink, NotLink,
etc   Perhaps its a bad idea. Not sure.  But all this is making me
think that, if we can invent the right link types and behaviors, the
URE could be and automatic, "built-in" part of the pattern matcher.

Alternate proposals invited.

**Comment by ngeiswei** [comment]
I've also been thinking about
```
MustBePresentLink
```
that way a pattern given to the pattern matcher would be a predicate, period. No need to have the pattern have a special meaning when it's in the pattern matcher or when it's somewhere else.

**Comment by linas** [comment]
Well, patterns are already "crisp-logic" predicates. The big AndLink that you use to wrap all the clauses (i.e. predicates) that specify a pattern behaves like a crisp-logic AndLink: all clauses must be satsified for the pattern as a whole to be satsified.  So I'm not sure what you mean when you say " have a special meaning when it's in the pattern matcher or when it's somewhere else." I can sort of guess what you mean, I can almost see it myself, but am not sure. its confusing.

If we just wanted crisp logic, we'd be programming in prolog. Cyc uses a prolog variant "cyclog" or something like that. ASP works great, the SAT solves underneath ASP are way faaaast. 

So part of what is spinning through my head is "what should pattern matching work like, when its uzzy or probablistic?" In some ways, its clear: the markov-chain demo gives one example. I think, I'm not sure, the markov-chain demo can generalize by using the PLN rules, instead of bayesian conditional probabilities. 

But in other ways, the answer is not clear.

**Comment by bgoertzel** [comment]
Somewhat pertinent to this, I have been figuring out a way to do something
ASP-like based on the Atomspace (i.e. map certain kinds of pattern-match
queries into SAT problems)....   I'll write up my thoughts next week
perhaps....  This pertains to a certain application project some of the
Ethiopians are working on...

-- Ben


On Mon, Apr 27, 2015 at 10:56 PM, Linas Vepštas <notifications@github.com>
wrote:

> Well, patterns are already "crisp-logic" predicates. The big AndLink that
> you use to wrap all the clauses (i.e. predicates) that specify a pattern
> behaves like a crisp-logic AndLink: all clauses must be satsified for the
> pattern as a whole to be satsified. So I'm not sure what you mean when you
> say " have a special meaning when it's in the pattern matcher or when it's
> somewhere else." I can sort of guess what you mean, I can almost see it
> myself, but am not sure. its confusing.
>
> If we just wanted crisp logic, we'd be programming in prolog. Cyc uses a
> prolog variant "cyclog" or something like that. ASP works great, the SAT
> solves underneath ASP are way faaaast.
>
> So part of what is spinning through my head is "what should pattern
> matching work like, when its uzzy or probablistic?" In some ways, its
> clear: the markov-chain demo gives one example. I think, I'm not sure, the
> markov-chain demo can generalize by using the PLN rules, instead of
> bayesian conditional probabilities.
>
> But in other ways, the answer is not clear.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/issues/1462#issuecomment-96686228>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by linas** [comment]
Since pattern matching is crisp, then in principle, all pattern queries
should be representable as a boolean SAT problem. In practice, its not
entirely clear how to best do this. Naively one would expect SAT to run
faster, however, perhaps e.g. with a pivoting search, PM might run as fast
as SAT. Its quite murky.

Almost doesn't matter, because no one is using the PM in any difficult or
stressful way: the current PLN rules use the pattern matcher in an almost
trivial way; none of the PLN rules are complex. The demos and unit tests
are far more stressful to the PM than any existing, actual application
(with the exception of the old question-answering chatbot, which made very
complex queries, which prompted this whole thing)

--linas

**Comment by linas** [comment]
Closing; I believe this work has been completed.
