### ISSUE TITLE
Adding too many atoms in a single scheme session segfaults

### ISSUE THREAD

**Issue by GarethNelson** [opencog/opencog#1626]
Tested with multiple examples trying to import an atomspace via the scm command on cogserver's shell, beyond a certain size (haven't narrowed it down yet) it segfaults.

Pasting into a telnet session and using netcat -q60 as in the NLP samples both yield the same result

	Stack Trace:
	2: basic_string.h:293	~basic_string()
	3: ??:0	killpg()
	4: ??:0	scm_vm_ip()
	5: ??:0	scm_call_4()
	6: ??:0	scm_at_abort()
	7: ??:0	scm_c_with_continuation_barrier()
	8: ??:0	scm_set_thread_cleanup_x()
	9: ??:0	GC_call_with_stack_base()
	10: ??:0	scm_with_guile()
	11: SchemeEval.cc:520	  opencog::SchemeEval::poll_result()
	12: basic_string.h:293	  opencog::GenericShell::poll_output()
	13: basic_string.h:725	  std::string::size() const
	14: ConsoleSocket.cc:232	  opencog::ConsoleSocket::OnLine(std::string const&)
	15: basic_string.h:301	~basic_string()
	16: ??:0	  boost::detail::add_thread_exit_function(boost::detail::thread_exit_function_base*)
	17: ??:0	start_thread()
	18: ??:0	__clone()

**Comment by GarethNelson** [comment]
Example of cogserver shell for the session that caused the above error:

guile> (ConceptNode "water")

(ConceptNode "Volume")

(ConceptNode "bone")

(ConceptNode "StaticObject")

(ConceptNode "Object")

(ConceptNode "plan_rule_list")

(ConceptNode "angry")

(ConceptNode "Unknown")

(ConceptNode "energy")

(ConceptNode "thankful")

(ConceptNode "High")

(ConceptNode "love")

(ConceptNode "Battery")

(ConceptNode "Structure")

(ConceptNode "MovableObject")

(ConceptNode "#drop")

(ConceptNode "plan_context_list")

(ConceptNode "psi_demand_goal_list")

(ConceptNode "Item")

(ConceptNode "Low")

(ConceptNode "13")
(ConceptNode "water")

guile> 
guile> (ConceptNode "Volume")

guile> 
guile> (ConceptNode "bone")

guile> 
guile> (ConceptNode "StaticObject")

guile> 
guile> (ConceptNode "Object")

guile> 
guile> (ConceptNode "plan_rule_list")

guile> 
guile> Connection closed by foreign host.

Connection was closed due to the segfault

**Comment by linas** [comment]
Hmmm ..  I regularly load much larger files without a problem.  There have been issues with guile trying to auto-compile large datasets, slowing things down ... 

What guile version are you using? 

I assume you did a git pull from master, within the last week or so?  

The stack trace above indicates that guile garbage collection (the GC_* call) is trying to run while printer thread is waiting for more output to get printed (poll_output/poll_result)   This suggests that poll_result is using some scheme object that has not been properly ref-counted, so that when GC runs, that object is reaped, and the next time it gets used, things crash.

A more detailed stack trace, from gdb, would be good. i.e. start cogserver in gdb, and wait for it to happen there.  because this is a race condition of some sort, instructions for some very reliable way for reproducing this is needed, as otherwise I cannot reproduce, and without that, probably can't fix, unless I get lucky.

There had been a bug fix in this general area,  maybe a few months ago, I don't recall...the bug-fix was in the atomspace code, not in the cogserver code, so you would have to git pull the atomspace code, build it, install it, then rebuilt the cogserver.

**Comment by linas** [comment]
closing; Stale and no progress in months.  I can't reproduce this based on the instructions above. If it is still an issue, open a new bug report...
