### ISSUE TITLE
Considering CFFI as an alternative for Cython

### ISSUE THREAD

**Issue by keyvan-m-sadeghi** [opencog/opencog#1700]
@inflector, Python maintainers,
I've recently came across [CFFI](https://bitbucket.org/cffi/cffi), it seems to have gained traction in the community, a value proposition is PyPy readiness, another is apparently less tedious binding code. I suggest someone checks it out.

**Comment by amirouche** [comment]
- The new way of doing `C++` bindings for pypy and **only pypy** is [cppyy](http://pypy.readthedocs.org/en/latest/cppyy.html#installation). The constraints with this solution is that CPython is out and that PyPy is still a moving target even if it's used in production (some issues might arise, but PyPy people are very receptive and will help, given proper feedback).

- Under [some condition cython bindings can work with PyPy](http://docs.cython.org/src/userguide/pypy.html)

- [cffi](https://cffi.readthedocs.org/en/latest/) is for ``C`` code only. If you want to use that, `C` wrappers of the C++ library must be created. It works on both CPython and PyPy but is kind of slower under CPython that cython bindings. By the way it's based on a tool developed at CERN, which heavily rely on C++, so it's not going to disappear.

My advice would have been to use C instead of C++ since the tools are readily available for that. Given that most of the code is written in C++ and you want to continue to write C++ code, it's better to use **cppyy** and write a similar library for Guile.

I know both Guile and Python, I'd like to help.

**Comment by linas** [comment]
I strongly discourage a shift to a different interface, simply because cython seems to be "good enough", and it would take a lot of work to get back to where we are now, with nothing to show for that effort.

We currently do not have anyone who is active in the project who cares enough about python/cython to actually fix any python/cython bugs.  There are currently 4 failing unit tests; all are cython/python, no one has fixed them yet.  The fixes are probably simple for maybe half the tests, maybe all; they used to pass, once upon a time...

Most importantly, we have a serious design flaw in the cython bindings that needs to be fixed: The "Handle" class must be removed ASAP.  The Handle should never have been exposed in cython, and it is a blocker for general cleanup in other parts of opencog.

**Comment by amirouche** [comment]
I will investigate the failing tests asap.

**Comment by linas** [comment]
I just now investigated the cython-uses-handles issue, and decided that perhaps it is not an issue; there is another way...
