### ISSUE TITLE
Loading VariableNodes from backing store 

### ISSUE THREAD

**Issue by bgoertzel** [opencog/opencog#1742]
Suppose the Atomspace already contains

SatisfyingSetLink (VariableNode "$X") (EvaluationLink (PredicateNode "humans") (ListLink (ConceptNode "eat") (VariableNode "$X")))

and then someone loads, from the backing store, the construct

SatisfyingSetLink (VariableNode "$Y") (EvaluationLink (PredicateNode "humans") (ListLink (ConceptNode "eat") (VariableNode "$Y")))

According to my understanding of the current code [please correct me if I'm wrong], these will look different because the VariableNodes have different names, so they won't be merged. But actually they are redundant; they  mean the same thing. 

Of course this is just a simple example, much more complex ones are possible.

Without VariableNodes, the basic merge rule is that two Nodes are the same if they have the same name and type; and two Links are the same if they have the same type and target-list

With VariableNodes, it's more complicated...

Let's use the term Scoping Link to mean any link that can specify a variable binding, e.g. BindLink, LambdaLink, SatisfyingSet, ForAll, etc. etc. 

Each Scoping link can be viewed as the root of an Atom-dag: follow the outgoing set of the ScopingLink, and the outgoing set of everything you find that way, etc. ... and you get the Scoping link's Atom-dag..

So the basic merge rule for Scoping links is: Two Scoping links are the same if they are roots of Atom-dags that are the same up to a renaming of the VariableNodes that they scope....

In theory this could be expensive to check; in practice currently our Scoping links don't scope extremely large variable lists, so there's not a big compute-time issue here...

The issue is to implement this merge rule for Scoping links...

(Of course, this would be relevant to any system for passing Atoms from one Atomspace to another (via ZMQ or whatever); it's just that with our current infrastructure it would only come up in the context of the backing store...)

**Comment by ngeiswei** [comment]
This is tied to the more general over-representation problem. We need an atomspace reduct engine, that would ideally (letting aside computation resource for now) run every time something has changed or is about to changed.

Once we have that atomspace reduct engine we can address that more specific problem with an alpha-equivalence reduction rule.

**Comment by bgoertzel** [comment]
Sure, one could handle this problem as a sub-case of a more general
reduction mechanism...

On Wed, Aug 26, 2015 at 11:14 PM, ngeiswei <notifications@github.com> wrote:

> This is tied to the more general over-representation problem. We need an
> atomspace reduct engine, that would ideally (letting aside computation
> resource for now) run every time something has changed or is about to
> changed.
>
> Once we have that atomspace reduct engine we can address that more
> specific problem with an alpha-equivalence reduction rule.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/issues/1742#issuecomment-135057388>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by linas** [comment]
To the best of my knowledge, the "atomspace reduct engine" is called the
URE.  What are missing are rules to handle cases such is this.

If you don't agree that the URE is the "atomspace reduct engine", then we
need to figure out what the URE is, because I would then be very confused...

**Comment by linas** [comment]
I humbly suggest that the phrase "merge rule" is a dangerous software architecture phrase, to be used with great caution, else you will get very unsatisfactory results.   There's a Zen koan called "mechanism not policy",  as old as software itself. It is rooted in the experience that, whenever you place policy into software, you end up with an incomprehensible system and unusable code. 

With this in mind, I was careful to remove all "merge rules" (aka merge policies) from the atomspace, and from the backend. My goal is to have the atomspace (plus backend) be very small and minimalistic, providing some basic generic tools allowing you to do whatever, completely shorn of any rules or merge policies at all. 

Policy is not bad; to get a high-quality user experience, you need good, strong policies. But they need to be isolated into their own layer or module, rather than infesting the system.

So, any merge rules, data scrubbing, normalization, etc. needs to happen in a different layer, some new layer. Nil previously talked about scrubbing the atomspace, to make sure that all atoms have the correct types (type checking); such a lyuer would be a good place to implement such things.

**Comment by bgoertzel** [comment]
I agree with this...

On Thu, Aug 27, 2015 at 1:30 AM, Linas Vepštas <notifications@github.com>
wrote:

> I humbly suggest that the phrase "merge rule" is a dangerous software
> architecture phrase, to be used with great caution, else you will get very
> unsatisfactory results. There's a Zen koan called "mechanism not policy",
> as old as software itself. It is rooted in the experience that, whenever
> you place policy into software, you end up with an incomprehensible system
> and unusable code.
>
> With this in mind, I was careful to remove all "merge rules" (aka merge
> policies) from the atomspace, and from the backend. My goal is to have the
> atomspace (plus backend) be very small and minimalistic, providing some
> basic generic tools allowing you to do whatever, completely shorn of any
> rules or merge policies at all.
>
> Policy is not bad; to get a high-quality user experience, you need good,
> strong policies. But they need to be isolated into their own layer or
> module, rather than infesting the system.
>
> So, any merge rules, data scrubbing, normalization, etc. needs to happen
> in a different layer, some new layer. Nil previously talked about scrubbing
> the atomspace, to make sure that all atoms have the correct types (type
> checking); such a lyuer would be a good place to implement such things.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/issues/1742#issuecomment-135117239>.
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"The reasonable man adapts himself to the world: the unreasonable one
persists in trying to adapt the world to himself. Therefore all progress
depends on the unreasonable man." -- George Bernard Shaw

**Comment by linas** [comment]
The context for this issue is seen in pull request https://github.com/opencog/atomspace/pull/241

**Comment by linas** [comment]
The idea that `(SatisfyingSetLink (VariableNode $X) (humans eat $X))` is the same thing as `(SatisfyingSetLink (VariableNode $Y) (humans eat $Y))` is called "alpha-conversion" or "alpha-renaming".  You can change $x to $y, but ONLY if it doesn't appear inside of some other atoms that are already using `VariableNode $Y`  because then you would accidentally have two different variables being given the same name.

**Comment by linas** [comment]
Closing, I think this got fixed a long time ago.
