### ISSUE TITLE
Dead link on opencog tutorial page

### ISSUE THREAD

**Issue by eddiemonroe** [opencog/opencog#2083]
As reported by Ean Schuessler:

---------- Forwarded message ----------
From: Ean Schuessler <ean@brainfood.com>
Date: Sat, Mar 19, 2016 at 5:16 PM
Subject: Another documentation problem
To: Eddie Monroe <eddiemonroe@gmail.com>

Go to the opencog tutorial:
https://github.com/opencog/opencog/blob/master/TUTORIAL.md

Read down to "automated program learning".

Under that try to click "moses-example.py".

404 not found.

**Comment by linas** [comment]
Looks like the python bindings for moses were removed.  If anyone really cares about this, they could be revived. Chris Poulin's 'poses' is a much better python API to moses, but remains quasi-proprietary (an earlier version can be obtained from  PLOS ONE (the Durkeheim project)).

**Comment by bgoertzel** [comment]
There is also a pretty good R binding for MOSES these days, in the bio-AGI
repository...

https://github.com/opencog/agi-bio

the associated scripts are a bit specialized for analyzing gene expression
and SNP data though...


On Sun, Mar 20, 2016 at 9:01 AM, Linas Vepštas <notifications@github.com>
wrote:

> Looks like the python bindings for moses were removed. If anyone really
> cares about this, they could be revived. Chris Poulin's 'poses' is a much
> better python API to moses, but remains quasi-proprietary (an earlier
> version can be obtained from PLOS ONE (the Durkeheim project)).
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/issues/2083#issuecomment-198816888>
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"I am Ubik. Before the universe was, I am. I made the suns. I made the
worlds. I created the lives and the places they inhabit; I move them here,
I put them there. They go as I say, then do as I tell them. I am the word
and my name is never spoken, the name which no one knows. I am called Ubik,
but that is not my name. I am. I shall always be.” -- Ubik

**Comment by AmeBel** [comment]
Rmoses is @ https://github.com/mjsduncan/Rmoses

**Comment by cosmoharrigan** [comment]
The Python bindings for MOSES were not removed; they are here:
https://github.com/opencog/moses/blob/master/moses/cython/opencog/pymoses.pyx

**Comment by bgoertzel** [comment]
hMM, wonder why the py-moses tutorial didn't work then...

On Sun, Mar 20, 2016 at 2:02 PM, Cosmo Harrigan <notifications@github.com>
wrote:

> The Python bindings for MOSES were not removed; they are here:
>
> https://github.com/opencog/moses/blob/master/moses/cython/opencog/pymoses.pyx
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/opencog/opencog/issues/2083#issuecomment-198855055>
>



-- 
Ben Goertzel, PhD
http://goertzel.org

"I am Ubik. Before the universe was, I am. I made the suns. I made the
worlds. I created the lives and the places they inhabit; I move them here,
I put them there. They go as I say, then do as I tell them. I am the word
and my name is never spoken, the name which no one knows. I am called Ubik,
but that is not my name. I am. I shall always be.” -- Ubik

**Comment by cosmoharrigan** [comment]
It looks like moses-example.py was removed, however.

**Comment by cosmoharrigan** [comment]
Here it is:
https://github.com/opencog/moses/blob/master/examples/moses.py

**Comment by eddiemonroe** [comment]
Fixed the broken link on the tutorial page.  #2084

**Comment by linas** [comment]
I lookked at the ttutorial a little more carefully. It needs a MAJOR overhaul, in my opinion.  It brings MOSES much too early. It wildly over-emphasizes python, which is  major mistake.  It recommnds pycharm, which is anotherr major mistake. 

The section on graph-rewriting is 100% incorrect -- it has nothing to with either constraint satisfaction or with boolean SAT.    It fails to mention forward and backward chaining -- where backward chaining *IS* an example of constraint satsifaction, but forward-chaining is not. Nowhere in opencog do we use boolean SAT, even though we should. 

The section on unit testing has nothing to do with tutorial-ness.

The python API has nothing to do with REST.  REST is a concept orthogonal to python -- it can be used with Java (and is used by the neo4j bindings)

The tutorial manages to COMPLETELY fails to mention the examples directory, where all the actual examples are located. 

The tutorial is such a complete and utter failure, that I suggest that maybe it should be completely deleted.  In this case, nothing would be better than something.

**Comment by linas** [comment]
Its not even targeted at the right repo --- moses is in a different repo, graph-rewriting is in a different repo, 

It fails to mention NLP entirely, which is about 3/4ths of what is in the opencog repo. The remaining 1/4th is divided between spacetime, spatial, the cogserver, attention allocation, pattern mining and openpsi -- of these it mentions only pattern-minig, which is about 5% of the total code.

**Comment by linas** [comment]
I mean, it doesn't even obey 80-char columns!! WTF!

**Comment by bgoertzel** [comment]
Yeah that is a deprecated tutorial ..a new one is in the works but not done
yet ...

http://wiki.opencog.org/wikihome/index.php/Hands_On_With_OpenCog

**Comment by linas** [comment]
I created pull request #2085 to remove this tutorial. However, due to cirlce-ci craziness, that pull request also manages to pull in all of the other outstanding, un-merged pull requests that I have.  Why the hell are we using circle-ci for this stuff?

**Comment by bgoertzel** [comment]
We are not using circle ci

However we can reconsider how jenkins and github are configured if it is
problematic...

**Comment by bgoertzel** [comment]
Hmmm.. so Linas, I am no expert on this stuff but I looked into this a
little bit...

It seems that what you mean by "circle ci"  (actually Jenkins now) is the
need for a PR to be up to date with master before a merge.  If I understand
correctly, this requires merging master onto the PR, right?

When I look at other pull requests I don't see mangled histories, it all
seems to make sense...

https://github.com/opencog/opencog/pull/2047
https://github.com/opencog/atomspace/pull/578
(two clean examples)

https://github.com/opencog/atomspace/pull/699
(this one has a merge conflict, yet still the history is just a couple of
merge-related entries, not a freakadelic mess)

https://github.com/opencog/atomspace/pull/604
(multiple merges, still readable history)

https://github.com/opencog/atomspace/pull/703
(a recent clean commit history from you yourself...)

It seems your recent PRs after 703 have all had unintuitively weird
histories, and I don't understand why -- I don't know how you're merging.
What are you doing differently since 703?

I asked Wenwei to create branches called "dev" on all the repos, which have
NO branch protection, so you can just merge there in pretty much any wacky
way you want to.   I wonder why you don't just merge into dev if you don't
like the branch protection.  Then Amen or Nil or Wenwei will merge your
changes into master since they don't mind the branch protection....  That
was kinda the point of creating the dev branches, which are now unused
though ;p

Apologies if I am misunderstanding something, I'm trying my best...

ben





On Mon, Mar 21, 2016 at 10:36 AM, Ben Goertzel <ben@goertzel.org> wrote:

> We are not using circle ci
>
> However we can reconsider how jenkins and github are configured if it is
> problematic...
> On 21 Mar 2016 10:34 am, "Linas Vepštas" <notifications@github.com> wrote:
>
>> I created pull request #2085
>> <https://github.com/opencog/opencog/pull/2085> to remove this tutorial.
>> However, due to cirlce-ci craziness, that pull request also manages to pull
>> in all of the other outstanding, un-merged pull requests that I have. Why
>> the hell are we using circle-ci for this stuff?
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/opencog/opencog/issues/2083#issuecomment-199088633>
>>
>


-- 
Ben Goertzel, PhD
http://goertzel.org

"I am Ubik. Before the universe was, I am. I made the suns. I made the
worlds. I created the lives and the places they inhabit; I move them here,
I put them there. They go as I say, then do as I tell them. I am the word
and my name is never spoken, the name which no one knows. I am called Ubik,
but that is not my name. I am. I shall always be.” -- Ubik

**Comment by schue** [comment]
Ok... not sure what happened... I need to look for which commit did what. 

Now if you hit https://github.com/opencog/opencog/blob/master/TUTORIAL.md it no longer exists! This URL is referenced from the README.md at the top of the opencog repository so a quick fix would be good. I've also noticed a few other dead links in the introductory pages. Do you want me to open separate issues for those?

**Comment by linas** [comment]
Ben, I'm not going to have this conversation.  I'm complaining about the
ankle chains, you're trying to understand why I feel that they're
uncomfortable. Its not a conversation that can possibly move forwards.

**Comment by linas** [comment]
Ean, the pull request opencog/atomspace#728 now eliminates the mention of the TUTORIALS.md page, and replaces it with a 4-paragraph description of what the atomspace is, and a pointer to the examples directory.  Its likely that the other "intro-to" pages are also in poor repair.   Dead links and bugs in github content should get github bug reports.  Dead links and inaccuracies in the wiki pages should get reported on the mailing list.

**Comment by linas** [comment]
closing, appears to be fixed.
