### ISSUE TITLE
AIML chatbot doesn't not give any response sometimes

### ISSUE THREAD

**Issue by leungmanhin** [opencog/opencog#2188]
Here is a way of reproducing it:

Generate the psi-rules using `aiml2psi.pl` for the aiml rules defined in `psychology.aiml` (https://github.com/hansonrobotics/HEAD/blob/master/src/chatbot/aiml/generic/psychology.aiml)

From Guile:
```
(use-modules (opencog) (opencog nlp) (opencog nlp aiml) (opencog openpsi))
(primitive-load "../opencog/nlp/aiml/aiml-rules.scm")

(aiml-get-response-wl (string-words "Are you nervous"))
```

And looks like it always gives me an empty ListLink
```
$1 = (ListLink
)
```

Is there anything I am missing?

**Comment by leungmanhin** [comment]
In addition to the above, if I do 
```
(aiml-get-response-wl (string-words "You need a psychiatrist"))
```
twice, it gives me an error, e.g.
```
scheme@(guile-user)> (aiml-get-response-wl (string-words "You need a psychiatrist"))
$2 = (ListLink
   (WordNode "What")
   (WordNode "if")
   (WordNode "it")
   (WordNode "didn't")
   (WordNode "happen?")
)

scheme@(guile-user)> (aiml-get-response-wl (string-words "You need a psychiatrist"))
ERROR: In procedure cog-type:
ERROR: In procedure cog-type: Wrong type argument in position 1 (expecting opencog atom): ()
```

**Comment by linas** [comment]
I can fix the "wrong type arg" message, but the lack of reply is "working as designed" -- there is a rule that says, "never say the same thing twice in a row", and so if the AIML rules only generate one response, the second time, it will be empty/blank.

**Comment by linas** [comment]
On Wed, Jun 15, 2016 at 1:49 PM, Ben Goertzel <ben@goertzel.org> wrote:
    Hmmm, I see...
    Do you mean "never say the same thing twice in a row" literally ,

Yes, that.

    or do you mean "never say the same thing twice in the same conversation?" 

That is what the HR python AIML chatbot does -- it records the *entire* conversation, and never says the same thing twice.
 
    ... if the latter, it seems maybe too strict, no?

Right, which is why I only look at the previous sentence.  More generally, there is an open to-do item, which says "don't get caught in a loop doing the same thing over and over".  (which is a form of mental illness, I had a friend who was hospitalized, because he got caught in such loops).

Right now, the "never say the same thing twice in a row" is a small, simple two-line check in the AIML code -- it can be moved to some other part of the chat subsystem -- however, it appears to be needed, because ... Vytas/David Hanson noted this and fixed it (in Wenwei's chatbot code).

**Comment by linas** [comment]
Actually, the "never say the same thing twice" logic is actually more complicated than it seems.  The code is here: https://github.com/opencog/opencog/blob/master/opencog/nlp/aiml/aiml.scm#L377-L402 

It loops 5 times, trying to get a sentence that is not a repeat.  If it succeeds, then it records "THAT" sentence.  The AIML mechanism depends on "THAT" being set to the previous response, and so, wherever the final check is made, the THAT variable needs to be set only afterwards.

**Comment by linas** [comment]
p.s. it is a USER ERROR to use the `string-words` function!! You MUST use `token-seq-of-sent`

The `string-words` function is a debugging function, it does not handle capitalization correctly, it does not handle punctuation correctly.  For example: `(aiml-get-response-wl (string-words "Are you nervous"))` fails but `(aiml-get-response-wl (string-words "are you nervous"))` works.  That's because all AIML rules are lower-case, and the upper-case "Are" results in no reply.

**Comment by linas** [comment]
Pull req #2197 fixes this.

**Comment by leungmanhin** [comment]
I see, thanks!
