### ISSUE TITLE
Guile terminated when calling cancel-thread

### ISSUE THREAD

**Issue by leungmanhin** [opencog/opencog#2214]
I have a question about threads in guile, the situation I am having can be reproduced by doing:
```
; Something that will still be running until cancel-thread is called
(define (test)
    (while #t (display 1) (sleep 3))
    (stv 1 1))


; Create a thread that calls the above scm function via a GroundedPredicateNode
(define tt
    (begin-thread
        (cog-evaluate! (Evaluation (GroundedPredicate "scm: test") (List)))))


; Call cancel-thread
(cancel-thread tt)
```

Then guile terminated with this:
```
scheme@(guile-user)> *** longjmp causes uninitialized stack frame ***: guile terminated
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x7338f)[0x7f6e2d52b38f]
/lib/x86_64-linux-gnu/libc.so.6(__fortify_fail+0x5c)[0x7f6e2d5c2c9c]
/lib/x86_64-linux-gnu/libc.so.6(+0x10abad)[0x7f6e2d5c2bad]
/lib/x86_64-linux-gnu/libc.so.6(__longjmp_chk+0x29)[0x7f6e2d5c2b09]
/usr/lib/libguile-2.0.so.22(+0x5b0fd)[0x7f6e2daf60fd]
/usr/lib/libguile-2.0.so.22(+0xd9e10)[0x7f6e2db74e10]
/usr/lib/libguile-2.0.so.22(+0xdd661)[0x7f6e2db78661]
/usr/lib/libguile-2.0.so.22(scm_call_with_vm+0xd0)[0x7f6e2db89ec0]
/usr/local/lib/opencog/libsmob.so(_ZN7opencog10SchemeSmob15throw_exceptionERKSt9exceptionPKc+0x8b)[0x7f6e2b552c3b]
/usr/local/lib/opencog/libsmob.so(_ZN7opencog16PrimitiveEnviron7do_callEP17scm_unused_structS2_+0x84)[0x7f6e2b552e94]
/usr/lib/libguile-2.0.so.22(+0xe212a)[0x7f6e2db7d12a]
/usr/lib/libguile-2.0.so.22(scm_call_3+0x2e)[0x7f6e2daff81e]
/usr/lib/libguile-2.0.so.22(+0xd4f65)[0x7f6e2db6ff65]
/usr/lib/libguile-2.0.so.22(+0x5b2ca)[0x7f6e2daf62ca]
/usr/lib/libguile-2.0.so.22(+0xe212a)[0x7f6e2db7d12a]
/usr/lib/libguile-2.0.so.22(scm_call_4+0x33)[0x7f6e2daff863]
/usr/lib/libguile-2.0.so.22(+0x5b9ff)[0x7f6e2daf69ff]
/usr/lib/libguile-2.0.so.22(scm_c_with_continuation_barrier+0x35)[0x7f6e2daf6a95]
/usr/lib/libguile-2.0.so.22(+0xd478c)[0x7f6e2db6f78c]
/usr/lib/x86_64-linux-gnu/libgc.so.1(GC_call_with_stack_base+0x12)[0x7f6e2d264fe2]
/usr/lib/libguile-2.0.so.22(+0xd414c)[0x7f6e2db6f14c]
/usr/lib/x86_64-linux-gnu/libgc.so.1(GC_inner_start_routine+0x53)[0x7f6e2d269d93]
/usr/lib/x86_64-linux-gnu/libgc.so.1(GC_call_with_stack_base+0x12)[0x7f6e2d264fe2]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8182)[0x7f6e2d885182]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f6e2d5b247d]
======= Memory map: ========
00400000-00401000 r-xp 00000000 00:42 4823                               /usr/bin/guile-2.0
00601000-00602000 r--p 00001000 00:42 4823                               /usr/bin/guile-2.0
00602000-00603000 rw-p 00002000 00:42 4823                               /usr/bin/guile-2.0
02599000-042e6000 rw-p 00000000 00:00 0                                  [heap]
7f6e14000000-7f6e14021000 rw-p 00000000 00:00 0 
7f6e14021000-7f6e18000000 ---p 00000000 00:00 0
...
```

Is there anything I can do to avoid this?

**Comment by linas** [comment]
I guess its a guile bug.  Its also still a bug in guile-2.1.3 -- I just tried.

Thread cancellation is considered to be evil, and it is the one thing that google left out of bionic -- the Android C library, simply because of its difficult, invasive nature -- every system call needs to have a wrapper/check for cancellation.  its really hard to unwind stacks if a cancellation occurs when an exception is thrown at the same time. If a signal is sent at the same time, also, its even harder. Its a huge giant hairy mess, just in the gnu C library. 

Add to that mess the idea that you also have to safely unplug garbage collection, environments, continuation barriers, Ugh.  So I am not completely surprised. Since Android uses Java, these would be issues there, also, although Java does not have continuations.

If you want to exit a thread, then just periodically check some flag.  Deep under the covers, that is all that thread cancellation does, anyway, except that, because its so deep under the covers, below signals and exceptions and system calls, its complicated.

BTW Note that there exist ParallelLink and JoinLink for creating threads in Atomese See wiki for details.

**Comment by linas** [comment]
https://android.googlesource.com/platform/bionic/+/ics-mr0/libc/docs/OVERVIEW.TXT#148

**Comment by linas** [comment]
http://advogato.org/person/slamb/diary.html?start=49 -- look for the word "cancel" about 1/5th of the way down. (the 9 Nov 2006 post)

**Comment by leungmanhin** [comment]
I see, calling cancel-thread is really a bad idea... I'll try something else instead, thank you for the info!
