### ISSUE TITLE
Replace REST by gearman in the pattern miner

### ISSUE THREAD

**Issue by linas** [opencog/opencog#2225]
The pattern miner has a client-server as well as a native mode; the client-server should be built separately from the core miner -- in part because it has its own dependency on a REST module.

Also: the rest module in the pattern miner should probably be replaced by the gearman infrastructure.

**Comment by bgoertzel** [comment]
@linas  -- about replacing REST with gearman for the distributed pattern miner....   I can potentially assign someone in Addis to work on this.   However, I am not 100% clear on the value or importance of doing this.  I am not an expert on either REST or gearman.   What advantages will come from using gearman instead of REST here?  I do anticipate heavy use of distributed pattern mining during the next 6 months for various commercial OpenCog project, so this is a relevant issue to get right.   @cassiopennachin your view on this may also be valuable... thanks...

**Comment by pennachin** [comment]
Ben, I don't know the pattern miner implementation in detail, but I think Linas is right.  In principle it's a bad idea to add another dependency for the job of distributing tasks around. I'm fairly confident gearman can do the job here, and it's better integrated with the rest of the system, so using it would make maintenance and extension easier. Also, gearman is lower overhead than REST, but I don't know how much that would matter for this particular usage scenario. 

I'd say this isn't urgent but is definitely worth doing from a "code health"/technical debt perspective and would be a useful task for someone learning the pattern miner.

**Comment by ngeiswei** [comment]
This will likely never happen. The new URE pattern miner will probably rely on a more abstract infrastructure to distribute its computations.

**Comment by linas** [comment]
I'm re-opening till discussion clears up. I don't mind closing this particular issue as being "too gearmanish"; however, there is a generic architectural issue: what is the best way to do distributed processing with opencog?  Gearman was a baby-step in a better direction.

**Comment by ngeiswei** [comment]
The pattern miner is being obsoleted by the new URE-based pattern miner. As soon as the new pattern miner supports surprisingness I'll remove the old pattern miner from the code base, which will obsolete this issue as well. 

By more abstract I actually mean that in order to make the new pattern miner distributed suffices to make the URE distributed.

**Comment by linas** [comment]
Oh. OK.  I'm not gonna create an issue titled "make atomspace and URE fully distributed" mostly because we know we need this, we know that this is large and multifaceted, and requires multiple, interacting subsystems, and seems likely to generate much heat and little light, until it gets full-time focus from a real systems architect.
