### ISSUE TITLE
Generate speech from r2l structure

### ISSUE THREAD

**Issue by ngeiswei** [opencog/opencog#2238]
I'm unable to generate speech from r2l-like output without having the to-be-generated sentence and parse already there. As a result I cannot generate speech of inferred knowledge.

See below the steps to reproduce the problem. 

1. enter chatbot-psi (`guile -l "chatbot.scm"` under `opencog/opencog/nlp/chatbot-psi`)
2. `(chat "Robert likes pizza")`
3. save in a file the SetLink corresponding to the r2l output (fetch all SetLinks, it is one of the latests, containing over a dozen atoms, all closed -- no free var)
4. save as well the word nodes `"Robert"` `"likes"` `"pizza"``
5. exist chatbot-psi
6. enter chatbot-psi again
7. load the previously saved SetLink and word nodes
8. `(chat "Alice likes pizza")`
9. `(chat "What does Robert like")`

the given answer is
```
Alive likes pizza
```
while it should be
```
Robert likes pizza
```

**Comment by ngeiswei** [comment]
I should add that the problem doesn't seem to come from sureal. If do instead

1. enter chatbot-psi
2. `(chat "Alice likes chicken feet")`
3. `(Word "Robert")
4. `(sureal (Set (Evaluation (Predicate "likes") (List (Concept "Robert") (Concept "feet")))))`

I do get
```
Robert likes chicken feet
```

Word "Robert" wasn't saved in the initial trial, but even saving it alongside the r2l SetLink doesn't fix it.

**Comment by ngeiswei** [comment]
However, calling sureal on the following

```
(sureal
   (SetLink
      (InheritanceLink
         (ConceptNode "Robert@2291e65a-e782-45ed-a849-90eabb0d9c1b")
         (ConceptNode "Robert" (stv 0.028571429 0.0012484394))
      )
      (ImplicationLink
         (PredicateNode "likes@44a7a36f-07e5-48ec-bd51-7dd2277f3464")
         (PredicateNode "like" (stv 0.25 0.0012484394))
      )
      (InheritanceLink
         (ConceptNode "pizza@31c87ccb-0f52-4c05-8112-53c16cc294e3")
         (ConceptNode "pizza" (stv 0.028571429 0.0012484394))
      )
      (EvaluationLink
         (PredicateNode "likes@44a7a36f-07e5-48ec-bd51-7dd2277f3464")
         (ListLink
            (ConceptNode "Robert@2291e65a-e782-45ed-a849-90eabb0d9c1b")
            (ConceptNode "pizza@31c87ccb-0f52-4c05-8112-53c16cc294e3")
         )
      )
   )
)
```
returns the empty list. I suppose sureal should be able to return
```
(("Robert" "likes" "pizza"))
```
Right?

**Comment by ngeiswei** [comment]
Sorry to slam you with messages. I'm reporting my progress in case someone comes by and happens to be able to help.

According to `opencog/nlp/sureal/surface-realization.scm`If the SetLink contains an interpretation it will just output the corresponding existing sentence. Otherwise it will call `create-sentence` which ultimately calls `sureal-match` which call C++ function `do_sureal_match`.

The question then is, what are the requirements of do_sureal_match` in order to generate a sentence. Looking at the sureal unit tests I need no test using instances `"likes@..."` instead of `"likes"`, so maybe that's why it doesn't work. I guess I could generate structure without instances. Yet the fuzzy pattern matcher will try to select as answers the syntactically most similar structures to the query, and so I don't see how my inferred structure could be handed to sureal then. Anyway, more to investigate...

**Comment by bgoertzel** [comment]
Nil,

I talked to Man Hin and Amen about this a bit...

What they said is roughly as follows.

Suppose that you feed in the sentence "Pigs are very cute" into the
Atomspace, retaining all the outputs of nlp-parse

Next, suppose that you feed in the sentences "Dogs are slightly ugly" and
"Fred is a dog"  retaining all the outputs of nlp-parse

Suppose that PLN draws the conclusion corresponding to "Fred is slightly
ugly" (expressed in Atomese, not in English... i.e. PLN derives the R2L
output corresponding to "Fred is slightly ugly" (let's call this C) ) ...

Then I believe that, if you feed C to the microplanner, it should invoke
sureal in a way that leads to the sentence "Fred is slightly ugly" getting
produced...

ON THE OTHER HAND ... if when you feed in "Dogs are slightly ugly" and
"Fred is a dog" you do NOT retain all the outputs of nlp-parse in the
Atomspace, but only retain the output of R2L on these input sentences --
THEN I think the microplanner/sureal will not succeed at surface-realizing
from C ...

The point is that sureal needs the links between e.g. the ConceptNode for
"dog" and the WordNode for "dog" (which then has links to the link-parser
dictionary entry for "dog" ...)....   These Atoms are produced when parsing
a sentence involving "dog" such as "Dogs are slightly ugly" or "Fred is a
dog" ...

Later on we will improve the microplanner to do word selection as a
separate process ... so that if the ConceptNode that PLN comes up with is
not already linked to some WordNode with a link grammar dictionary entry,
then the word-selection process will find a set of Atoms that represent
that ConceptNode to a reasonable approximation...

-- Ben




On Mon, Jul 4, 2016 at 3:49 PM, ngeiswei <notifications@github.com> wrote:

> Sorry to slam you with messages. I'm reporting my progress in case someone
> comes by and happens to be able to help.
>
> According to opencog/nlp/sureal/surface-realization.scmIf the SetLink
> contains an interpretation it will just output the corresponding existing
> sentence. Otherwise it will call create-sentence which ultimately calls
> sureal-match which call C++ function do_sureal_match.
>
> The question then is, what are the requirements of do_sureal_matchin
> order to generate a sentence. Looking at the sureal unit tests I need no
> test using instances"likes@..."instead of"likes"`, so maybe that's why it
> doesn't work. I guess I could generate structure without instances. Yet the
> fuzzy pattern matcher will try to select as answers the syntactically most
> similar structures to the query, and so I don't see how my inferred
> structure could be handed to sureal then. Anyway, more to investigate...
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/opencog/opencog/issues/2238#issuecomment-230227008>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFolXFUY1_FVucKLwaxgCEZTwnT89Tf-ks5qSLsNgaJpZM4JEC7x>
> .
>



-- 
Ben Goertzel, PhD
http://goertzel.org

Super-benevolent super-intelligence is the thought the Global Brain is
currently struggling to form...

**Comment by leungmanhin** [comment]
Yes like Ben said that's why simply feeding only a SetLink to sureal may not work as those "instance" nodes are "disconnected" (say, from their word instances)

Also the fuzzy matcher in the chatbot may be annoying, so if you just want to generate a sentence, try using `gen-sentences` (https://github.com/opencog/opencog/blob/master/opencog/nlp/fuzzy/fuzzy.scm#L49), which will pass a set of atoms to microplanner and sureal for sentence generation

**Comment by ngeiswei** [comment]
Thanks for your feedback, guys. I actually tried to use the microplanner but it seems to freeze or something.

Anyway, at this point I think I start to understand how sureal operates. The fact that I'm already able to generate "Robert likes pizza" on the model of "Alice likes pizza" is very good. So my plan is to

1. Turn r2l outputs like "instance of Alice instance-likes instance of pizza" into "Alice likes pizza"
2. Use this to infer new knowledge
3. Pass this knowledge to sureal (assuming that grammatically similar sentences as present)

this should work! I didn't know sureal was able to do that, which is why I didn't come up with that plan before. Once I have a demo of that, I'll still need to have the NLP pipeline somehow being able to fetch the inferred knowledge to answer some query. But it's already a narrower problem.
