### ISSUE TITLE
Support nested random tag in AIML chatbot

### ISSUE THREAD

**Issue by leungmanhin** [opencog/opencog#2395]
It seems that the chance of using an AIML rule that contains nested random tags, for example:
https://github.com/hansonrobotics/HEAD/blob/master/src/chatbot/scripts/aiml/generic/default.aiml#L8192
https://github.com/hansonrobotics/HEAD/blob/master/src/chatbot/scripts/aiml/generic/client.aiml#L2422
https://github.com/hansonrobotics/HEAD/blob/master/src/chatbot/scripts/aiml/generic/interjection.aiml

is not negligible (might be 10-20%, roughly speaking...), in this case I think we'll have to support it as well

**Comment by leungmanhin** [comment]
This probably is one of the things that I'll try to do next, but the aiml2psi conversion script is a little bit hard to read... @linas it will be much appreciated if you have any advice on how to tackle this problem :)

**Comment by linas** [comment]
Ugh.  That perl script is a hacky mess.  Handling nesting might be icky.

What it currently does is to count how many alternatives there are -- which is easy, because all of the alternatives are in the same place, and then create N unique, distinct rules, giving each rule a probability of 1/N.

I guess that one could, for each of the N choices, make a recursive call back into the system, then grab the output and adjust the wight by 1/N.   There are certainly other parts of the code that make recursive calls, so it does kind-of-mostly work.   However, since the whole thing was hacked, the handling of state is not clean, so you will have to figure out who clobbered what state, and save/restore that by hand.

I coded up the whole thing by trial-and-error.  I thought it would take a few days, it took a few weeks.

**Comment by leungmanhin** [comment]
Yes some of the rules are very messy, converting all of them is quite a pain... thanks I'll take a look

**Comment by linas** [comment]
OK, let me know if you are suffering over this.

**Comment by linas** [comment]
@leungmanhin  I believe that you implemented this -- if so, can you close this bug?

**Comment by leungmanhin** [comment]
oh yes, implemented in https://github.com/opencog/opencog/pull/2407, closing it
