### ISSUE TITLE
C++ exception caused by run-chatbot.scm

### ISSUE THREAD

**Issue by StrangeTcy** [opencog/opencog#2414]
I'm trying to run `guile -l run-chatbot.scm`, and it complains that 

>  ?: 0 [opencog-extension c-start-cogserver (# "../lib/opencog-chatbot.conf")]
> 
> ERROR: In procedure opencog-extension:
> ERROR: Throw to key `C++-EXCEPTION' with args`("c-start-cogserver" "bind: Address already in use")'.

So I `pkill cogserver`, hoping it would free the address, but when I `guile -l run-chatbot.scm` again, the same error occurs.
How can I fix that?

**Comment by StrangeTcy** [comment]
I used `lsof -i` to list all process and ports they're listening on, and I killed anything remotely relevant to ports 17001 or 17004. And the error persists.

**Comment by StrangeTcy** [comment]
One workaround for this is fiddling with the `../lib/opencog-chatbot.conf`, but it doesn't solve the problem.

**Comment by linas** [comment]
If you have other telnet sessions trying to connect to those port numbers, the operating system won't release them. There's some algorithm involving SYN and FIN packets and some timeouts, what in bad situations, can be minutes.

**Comment by StrangeTcy** [comment]
Killing processes and checking for effect has lead me to believe that I've just used `Ctrl+Z` to stop `guile`, but it was still using the necessary port.
Unless further experiments reveal something radical, this issues should soon be closed, I think.

**Comment by linas** [comment]
Heh. Yes, control-Z just suspends a process, without actually putting it in the background. You have to say "bg" to actually back-ground it.  However, saying "bg" will also dettach it from the controlling tty, so you will no longer be able to type into its input line.  Yes, control-Z does not actually kill the thing, so, yes, of course, it will still be using the port, until such time as you do kill it or otherwise exit.

p.s. "fg" put a suspended process back into the foreground, reattaching the tty, so you can send it input, again. 

"jobs" will list all of the running jobs on this tty, including those that are suspended

**Comment by linas** [comment]
closing per remarks
