### ISSUE TITLE
No POS is assigned to the word 'which' in some cases

### ISSUE THREAD

**Issue by leungmanhin** [opencog/opencog#2429]
When doing:
```
(nlp-parse "She kept an organized record of which employees took their vacations.")
```
There is no `PartOfSpeechLink` generated for the word instance of "which", should there be one anyway?

**Comment by anitzkin** [comment]
Oy.  This could be a thorny one.  I would probably need to get the system running on my home PC to tell you exactly how it fits in with the current version of LG and Relex, (I mean, what did LG do with it?) but I'm guessing that the problem is the ambiguity of "of which" . . . 

It's a garden path sentence; that means that as you go through it, if you just parse up to "of which" you're going to think that the "which" is a relative pronoun, as it would be if the sentence said:

"She kept an organized record of which her boss had no knowledge."  

Where "of which" is, conceptually, is a modifier of "knowledge"; Her boss had no knowledge of the record.

But this is all wrong for the sentence you present, in which "which" is not a relative pronoun; it's now an interrogaticve adjective; there are a variety of more technical ways to describe it, but the point is that it modifies employees and implies a variable as in "Which employees tooke their vacation?"

All words have a "part-of-speech" and they are very useful for Relex.  I can't remember what LG does with a case like this; what did it do?

Sorry, if I ever succeed in installing Ubuntu and Opencog on the 2005 Dell I just inherited I'll take some action on these things :-(

**Comment by linas** [comment]
link-grammar currently generates this:
```
                  +-----------Os----------+     +-----------CV--------->+                
    +----->WV---->+     +------Ds**x------+     +-----Cs-----+          +-------Op------+
    +--Wd--+--Ss--+     +--PHv-+-----A----+--Mj-+-Jw+        +----Sp----+      +---Dmc--+
    |      |      |     |      |          |     |   |        |          |      |        |
LEFT-WALL she kept.v-d an organized.a record.s of which employees.n took.v-d their vacations.n 
```
which looks correct to me. I suppose one could argue that a determiner link is needed from "which" to "employees", to clearly indicate that "which" is acting as a determiner, here.

**Comment by linas** [comment]
Recall: link-grammar does NOT generate coarse-grained parts-of-speech, only relex does this.  What link-grammar does do is generate "fine-grained" parts of speech, which are the disjuncts themselves.

**Comment by linas** [comment]
Actually, the LG output was not quite right -- the new modern LG expects links pointing directly at head-verbs.  In this case, the link was absent, which screwed things up.  Fixed in opencog/link-grammar#396  The new parse is this:
```
                  +-----------Os----------+                                               
    +----->WV---->+     +------Ds**x------+     +-----------CV---------->+-------Op------+
    +--Wd--+--Ss--+     +--PHv-+-----A----+--Mp-+QI*d+--Dmcw--+----Sp----+      +---Dmc--+
    |      |      |     |      |          |     |    |        |          |      |        |
LEFT-WALL she kept.v-d an organized.a record.s of  which employees.n took.v-d their vacations.n 
```
and you can now observe the QI link indicating the interrogaive nature (QI meaning "inversion" -- as opposed to "which of the...") and the D link indicating its a determiner.

**Comment by anitzkin** [comment]
Yeah, that looks pretty good to me -- and I recall that I installed a whole bunch of stuff in Relex and R2L for dealing with "interrogative determiners" as I think we called them.  So, again, I'm guessing that if Relex isn't dealing well with this one, it might be because of its ambiguous resemblance to a relative pronoun.  Perhaps if you show me the full Relex output for this one, I can say something more helpful . . .

**Comment by linas** [comment]
.. and since there is now a D link between "which" and "employees", the "which" now gets a part-of-speech  stuck onto it.  So I think that is fixed.

**Comment by leungmanhin** [comment]
Yes I get it now with the latest LG
```scheme
(PartOfSpeechLink (stv 1 1)
   (WordInstanceNode "which@0ced7b1a-272b-43e0-bb03-f9c6d27336e4")
   (DefinedLinguisticConceptNode "det")
)
```
thanks a lot!
