### ISSUE TITLE
cogserver is not handling concurrent connections properly

### ISSUE THREAD

**Issue by andre-senna** [opencog/opencog#2594]
We have opencog with a cogserver listening for commands. In the server side we have:
```
(define (function-1 ticket)
    (cog-logger-info "CALLED function-1 ~s" ticket)
    (string-append "return-1-" ticket)
)

(define (function-2 ticket)
    (cog-logger-info "CALLED function-2 ~s" ticket)
    (string-append "return-2-" ticket)
)
```

The client perform N cycles. Each cycle is something like:

1 - Call function-1 passing a unique ticket
2 - Expect the proper answer
3 - Call function-2 passing another unique ticket
4 - Expect the proper answer 

When we spawn a lot (10+) of concurrent clients, cogserver will fail in one of the following manners:

(a) It just don't return anything for one of the function calls
(b) It re-do the call of the previous function just before processing a given function call

You can reproduce this behaviour using the files under opencog/tests/testCase1 in this branch: https://github.com/andre-senna/opencog/tree/cstest

(1) Start the server with "guile -l ../tests/testCase1/server.scm"
(2) Spawn several instances of client with "../tests/testCase1/client.tcl id n" where "id" identifies the client instance and "n" is the number of desired cycles (10 instances and n = 50 should suffice to see the error)

I'm sorry but I've used a simplification of my test script (which is in TCL) as the client. You may need to apt-get install tcl. 

After making the function call, the client waits 1s before trying a non-blocking "gets" in the socket. I've tested with delay as large as 5s with the same results. Error (b) is a lot least frequent than (a). You may need a larger n and/or a larger number of client instances to see it.

**Comment by andre-senna** [comment]
BTW we'are using the stable branches for opencog and atomspace

**Comment by linas** [comment]
I'll take a look.

**Comment by linas** [comment]
I just tightened up ShellUTest, which does a parallel send like that, to check the reply lengths, and do not see any issue there.

**Comment by linas** [comment]
Hmm. From what I can tell, this is a "user error"  ... I'm reading through the example: -- you re-use the same socket, but do not provide any mechanism to block or wait for an answer to come back. In fact, the code explicitly marks the socket non-blocking: here:  https://github.com/andre-senna/opencog/blob/cstest/tests/testCase1/client.tcl#L47 . As a result, you will explicitly miss any packets that are in-flight, over the net, and will only receive them next time around.

I've double-checked for this in an expanded unit test:  here: https://github.com/opencog/opencog/blob/master/tests/server/ShellUTest.cxxtest#L96-L155

lines 98-107 open a scoket to the cogserver.
lines  108-113 put it into the scheme shell
Next, a big loop, so that the socket is re-used for the next 60 messages.

lines 116-119 send some work on the socket.
lines 124-134 receive on the socket, in a non-blocking fashion. 
line 139: ***if*** the finished token is received, then we know that all of the reply has been received; else, loop around and wait for more data to arrive.

lines 145-153: verify that the answer is exactly what was expected.

lines 259-262: start 20 different threads. 

The unit test works... I don't know tcl well-enough to build the analogous tcl version.

**Comment by linas** [comment]
I just added comments to the code, so the above line numbers are a bit off now. Should still be clear.

**Comment by linas** [comment]
See also bug #2602 -- it is possible you are being bitten by that.   I have a fix for that, will push shortly.

**Comment by andre-senna** [comment]
Yes, probably. But this explains only the error (a). It doesn't explain error (b).

I've shortly investigated your test case and it seems like tik_tik_tik() is not properly testing for the error (b). If cogserver erroneously re-send the previous request (in a given thread)  your test will pass because both answers (the correct answer and the answer of the erroneously sent request) will be concatenated in "reply".

**Comment by linas** [comment]
do you have a test case? From what I can tell of the tcl code, you're simply getting the results, the second time, that you didn't get, the first time.  Also, in testcase1, you start not one but two cogservers... the second also uses the default port, so I assume there are error messages with regard to that.

**Comment by andre-senna** [comment]
We have a workaround for this behaviour so I think its ok to close this issue.
