### ISSUE TITLE
Clean the pattern miner (part I)

### ISSUE THREAD

**Issue by ngeiswei** [opencog/opencog#2615]
- [x] The unit test `tests/learning/PatternMiner/PatternMinerUTest.cxx` should be completed. That is the result should be checked. Also, all files, such as `ugly_male_soda-drinker_corpus.scm`, as well as all code, if any, pertaining to testing should be moved out of `opencog/learning/PatternMiner` back to the unit test directory.

- [x] Remove deprecated AtomSpace calls. See #2567 . See https://github.com/opencog/atomspace/blob/master/opencog/atomspace/AtomSpace.h#L553 for examples of deprecated methods. So for instance the following call of `AtomSpace::is_node(h)` https://github.com/opencog/opencog/blob/master/opencog/learning/PatternMiner/PatternMiner.cc#L58 should be be replaced by `h->isNode()`

- [x] Less important, but it would nice to replace the `StringManipulator` calls by boost string algorithms, so we can get rid of this redundant/useless class.

- [x] Disentangle the REST interface from the pattern miner core. See #2225. It would be good if the pattern miner could still be used, single threaded if necessary, when the user doesn't have cpprest installed.

- [ ] Replace the REST interface by the gearman interface (the idea is that gearman is strong/better/faster than the rest API's)

**Comment by shujingke** [comment]
The top 4 tasks have finished. I left the test data file and test agent in the directory , because people who want to try Pattern Miner can try to launch it from Cogserver.
The last task is a relatively bigger task, should not belongs to "clean up" - we can open a new issue for it. This issue can be closed I think.

**Comment by linas** [comment]
The gearman interface is already implemented, it mostly works (it passes unit tests).

By contrast, REST is just plain ugly and complicated and badly designed -- its crap code.  I wish burning and flaming death unto REST.  (Its not that Gearman is great -- its fairly minimal -- but it is better than REST -- at least, it provides some basic management utilities)

All this is besides the point -- distributed operation is orthogonal to the pattern-miner algorithm; the two should not be mixed together, as they are unrelated.  They should co-exist in different layers, at different levels of abstraction. We should have one layer that can perform pattern mining, and a completely different layer that can aggregate results, whether from pattern mining, or from some other data processing system within opencog (as we have several of these)

**Comment by shujingke** [comment]
Distributed codes have already been separated from the Pattern Miner core, it won't be built when the users have no cpprest in their machine. Now it is still located in the Pattern Miner dictionary, just for convenient because it uses the Pattern Miner core, and it's easier for people to find it.  From the perspective of codes, it's not on the same layer of the core - it depends on the core, has its own agents to execute the distributed version. 

Replace REST with gearman is a good idea, but not super urgent I think. Will do it if I have time after finish Pattern miner Scheme API.  Maybe by then, something better than gearman will come out that we can use : )

**Comment by ngeiswei** [comment]
I'm closing, replacing REST by gearman is an issue on its own.
