### ISSUE TITLE
Security: Authentication bypass in go-irc.cc

### ISSUE THREAD

**Issue by Shinkurt** [opencog/opencog#2701]
opencog/opencog/nlp/irc/go-irc.cc:311 says:

`const char *login = getlogin();` -- which I believe is an invalid way to check for authentication in this specific scenario, because It's often easy to fool getlogin. Sometimes it does not work at all, because some program messed up the utmp file (happens quite a lot) . Often, it gives only the first 8 characters of the login name. The user currently logged in on the controlling tty of the program need not be the user who started it. Avoid getlogin() for security-related purposes.

Suggestion: Use getpwuid(geteuid()) and extract the desired information instead.

**Comment by linas** [comment]
That's simply not how IRC works. There is no authentication happening here; there's no security, the login is just a displayed string on IRC and it can have any value whatsoever.  The only goal here is to provide some value, any value at all. Its not a credential.

**Comment by Shinkurt** [comment]
Oh sorry, in my case, we had IRC bots that verify users when we join a channel. (so our nicks are reserved for us, and I figured that was what this IRC bot was doing. -- or should) -- there is no way to confirm who the user is other than accepting the nick in this case -- which means I am reporting an authentication bypass where there is no authentication. -- pointless if there are no users that have priv over the bot (like admins) -- so they can't be spoofed.

**Comment by linas** [comment]
On IRC, any bot can be run by any user. Recall that any user can download bot code off the net, make whatever hostile modifications they want to, then compile it (if its C) or just-plain run it (if its python or perl) -- there is nothing that anyone can do to stop this.  

Realize that everyone on the planet can get root on some network device, and since they have root, there is no admin that can stop them from running arbitrary code.
