### ISSUE TITLE
Load path issue in pln-trail-1.scm

### ISSUE THREAD

**Issue by eddiemonroe** [opencog/opencog#2773]
I get this error when loading module (opencog nlp chatbot-psi)
```
scheme@(guile-user)> (use-modules (opencog nlp chatbot-psi))
While compiling expression:
ERROR: In procedure primitive-load-path: Unable to find file "opencog/pln/rules/term/deduction.scm" in load path
```
I traced it down to (I think) https://github.com/opencog/opencog/blob/master/opencog/nlp/chatbot-psi/pln-trail-1.scm#L344

I do see
/usr/local/share/opencog/scm/opencog/pln/rules/deduction.scm
but that doesn't get picked up by (pln-load-rules "term/deduction")
Perhaps the install directory is not correct?

Adding 

    (add-to-load-path "/home/eddie/hansonrobotics/opencog/opencog")
gets around the problem. But don't think we are requiring that in the load path for running opencog. Are we?

**Comment by leungmanhin** [comment]
I think this can be fixed by either updating the install directory (subdivide them into terms, propositional, wip etc) or updating the load path in chatbot-psi.
@ngeiswei I can easily update the load path in chatbot-psi to fix this issue, just want to confirm with you whether `/usr/local/share/opencog/scm/opencog/pln/rules/` is the desired install directory for the rules?

**Comment by ngeiswei** [comment]
@leungmanhin I'm gonna update the install directories. Thanks.

**Comment by leungmanhin** [comment]
@ngeiswei thanks!
