### ISSUE TITLE
Linking to Guile in pattern-index

### ISSUE THREAD

**Issue by Dagiopia** [opencog/opencog#2938]
should building the pattern-index examples have linking to ${GUILE_LIBRARIES} ?? I'm not sure why there's no unresolved symbols error when linking... it works fine. but it should link to guile since it uses guile
https://github.com/opencog/opencog/blob/281850b70035f780f1aea3aed3320d2b55d5b41f/opencog/learning/pattern-index/CMakeLists.txt#L24-L33

**Comment by AmeBel** [comment]
It is because the examples use SchemeEval symbols from [smob library](https://github.com/opencog/opencog/blob/master/lib/FindAtomSpace.cmake#L84) and not symbols from libguile. The smob library, on the other hand, requires guile-libraries b/c it uses symbols from [libguile](https://github.com/opencog/atomspace/blob/master/opencog/guile/CMakeLists.txt#L29)

**Comment by Dagiopia** [comment]
thanks amen!
