### ISSUE TITLE
Different tokenizers being used for language learning

### ISSUE THREAD

**Issue by leungmanhin** [opencog/opencog#2968]
There is one thing that may potentially be a problem. When doing random parses for each input sentence, the tokenizer being used there seems to only split the sentence by whitespace, so a punctuation will be considered as part of a word and word-pairs like this would be generated (note the word `parent.`):

```
(EvaluationLink (ctv 1 0 1)
   (LinkGrammarRelationshipNode "ANY")
   (ListLink
      (WordNode "Mom" (ctv 1 0 648))
      (WordNode "parent." (ctv 1 0 144))
   )
)
```

Later on when we do MST-parse, a different tokenizer is used which tries to identify punctuation and consider them as separate words. So in the above example two `WordNodes`, `(Word "parent")` and `(Word ".")`, instead of one will be created for MST-parsing. This seems to be problematic because the system will think that there is no **Mom-parent** observed (and indeed there is only **Mom-parent.** observed) and as a result generates no link between "Mom" and "parent" and may not even give a complete parse in the worst possible case.

I think at least the same tokenizer should be used for both processes. @linas @bgoertzel what do you think?

**Comment by linas** [comment]
Several unrelated comments:

First,  that is some kind of bizarre/new bug I have not seen before. If you look more closely, you'll see that the period is split away from the word, but then the word is printed with the period. I'm investigating that now.  This does not happen with the link-grammar command-line client, but only with the atomese-link-grammar wrapper. 

Second, it turns out that tokenization is extremely complex, its almost as complex as parsing, and interacts with it strongly: different tokenizations have different parses. The reasons for this complexity, and the current best-practices code was discussed extensively on multiple mailing lists, I don't want to try to summarize again here.  Its a fundamentally difficult problem. For now, the MST parser will continue to have to use the super-simple tokenizer until the tokenization infrastructure can be redesigned and upgraded. We've got a fancy tokenizer for link-grammar, but its more-or-less impossible to port it over and use it for MST.  Since any redesign for MST is a very big chunk of work, its best to leave it alone, for now, until we have to start dealing with languages other than English.  For English, the differences are mostly minor, and depend on the text.

**Comment by linas** [comment]
Anyway - kind of the point of the MST parsing is that what it generates gets replaced by the link-grammar perser, anyway, so that the link-grammar tokenizer gets used in the long run.  That's another reason to just leave MST in it's current hacky state.

**Comment by linas** [comment]
Seems that `linkage_get_word_byte_end()` is sometimes returning a value that is off-by-one.  This is a link-grammar function, so the fix will be made there.

**Comment by linas** [comment]
pull req #2969 fixes this - the bug was NOT in link-grammar, but a goofy miscalculaton in the opencog wrapper.

**Comment by linas** [comment]
If you want to think about tokenizing, here's a quick example that works in English:  consider the string "seasand" - should that tokenize into "seas and" or into "sea sand"?  Both are plausible, neither involves a typo.  If typos are allowed, then "seasoned" is another possibility.   The current link-grammar tokenizer does not do this for English, unless spell-guessing is turned on. For Russian, it explores all possibilities.  

Tokenization can be controlled per-language, by describing the kinds of prefixes, infixes and suffixes that might occur, and how many of them there might be. It's not clear that this is the best way to do  this, because, in some languages, prefixes can occur in the middle of words i.e. prefixes can occur after infixes (as long as they are followed by another infix). Then there are null-suffixes, with are grammatically active suffixes that don't have any text associated with them.  They are analogous to zero-copula in English, or zero-that, except that they occur at the end of the word.  Link-grammar does support null suffixes; they are used in Russian.  There was some work done for zero copula in English, but it was ugly.

So its a sticky problem, with no immediately obvious elegant solution.

**Comment by leungmanhin** [comment]
Now I can see tokenization is really complex... Back to this issue, it doesn't seem to be a printing issue though and I'm still having the same problem.

A more concrete example, when I do
```
(observe-text "Mom has a telescope.")
```
a node like `(WordNode "telescope." (ctv 1 0 24))` actually get generated and stored in DB, along with the count and MI with other words etc. And later on if I mst-parse the same sentence, the sections I get are
```
(Section (ctv 1 0 1)
   (WordNode "a" (ctv 1 0 24))
   (ConnectorSeq
      (Connector
         (WordNode "has" (ctv 1 0 24))
         (ConnectorDir "-")
      )
   )
)
 (Section (ctv 1 0 1)
   (WordNode "has" (ctv 1 0 24))
   (ConnectorSeq
      (Connector
         (WordNode "Mom" (ctv 1 0 24))
         (ConnectorDir "-")
      )
      (Connector
         (WordNode "a" (ctv 1 0 24))
         (ConnectorDir "+")
      )
   )
)
 (Section (ctv 1 0 1)
   (WordNode "Mom" (ctv 1 0 24))
   (ConnectorSeq
      (Connector
         (WordNode "has" (ctv 1 0 24))
         (ConnectorDir "+")
      )
   )
)
```

and the word "telescope" is missing. It's never observed because of the period appended to it during counting...

**Comment by linas** [comment]
and you did pull an rebuild? There was an off-by-one error that was causing the period to be printed.  You can test with  `Mom has a telescope--.`  and if you now get `telescope-` then you still have the off-by-one bug.

**Comment by leungmanhin** [comment]
Yes I did. It splits away the `--` and `.` for `Mom has a telescope--.`, but not the `.` for `Mom has a telescope`...

**Comment by leungmanhin** [comment]
Actually, I just rolled back the code to a point before the #2969 fix, parsed both `Mom has a telescope--.` and `Mom has a telescope.` and still saw the same behavior as I described in my last message. I haven't seen `telescope-` or the off-by-one error in general so far...

**Comment by linas** [comment]
I cannot reproduce this bug.  Starting with a clean, empty atomspace, and no database opened or connected, I do this:
```
(use-modules (opencog) (opencog exec))
(use-modules (opencog nlp))
(use-modules (opencog nlp learn))
(observe-text "Mom has a telescope.")

(cog-report-counts)
```
and no WordNodes or Sections are generated.  And they should not be -- Sections are generated later, by the MST parse.  Also: `(cog-get-atoms 'WordInstanceNode)` prints all word instances, and none of them have the concatenated period.  Also `(cog-prt-atomspace)` gruesomely dumps everything ...

**Comment by linas** [comment]
Similarly, starting with a clean, empty atomspace, no open databases, nothing, then this:
```
(use-modules (opencog) (opencog exec))
(use-modules (opencog nlp))
(use-modules (opencog nlp learn))
(mst-parse-text  "Mom has a telescope.")
(cog-report-counts)
(cog-get-atoms 'WordNode)
```
returns only this:
```
scheme@(guile-user)> (cog-report-counts)
$2 = ((SchemaNode . 1) (PredicateNode . 6) (WordNode . 6) (AnyNode . 4) (LinkGrammarRelationshipNode . 1))
scheme@(guile-user)>  (cog-get-atoms 'WordNode)
$3 = ((WordNode "a")
 (WordNode "has")
 (WordNode "Mom")
 (WordNode "###LEFT-WALL###")
 (WordNode ".")
 (WordNode "telescope")
)
```
 with no period at the end of `telescope`.

**Comment by leungmanhin** [comment]
Hmm... I cleaned the cache and followed your steps with a clean atomspace & no open database. I get exactly what you got when doing `mst-parse-text`, but not for `observe-text`... Here it is:

```
(use-modules (opencog) (opencog exec))
(use-modules (opencog nlp))
(use-modules (opencog nlp learn))

scheme@(guile-user)> (observe-text "Mom has a telescope.")
$1 = #f
scheme@(guile-user)> (cog-report-counts)
$2 = ((NumberNode . 120) (ListLink . 102) (EvaluationLink . 102) (SchemaNode . 1) (PredicateNode . 6) (WordNode . 5) (AnyNode . 2) (ReferenceLink . 120) (SentenceNode . 2) (ParseNode . 25) (ParseLink . 24) (WordInstanceNode . 120) (WordInstanceLink . 120) (PhraseNode . 1) (WordSequenceLink . 120) (LinkGrammarRelationshipNode . 1) (LgDictNode . 1) (LgParseMinimal . 1))
scheme@(guile-user)> (cog-get-atoms 'WordNode)
$3 = ((WordNode "a")
 (WordNode "has")
 (WordNode "telescope.")
 (WordNode "Mom")
 (WordNode "LEFT-WALL")
)
```
I understand no Sections will be generated at this stage, but I don't understand why no WordNodes are generated? Because I can see `LGParseLink` generates ReferenceLinks that connect WordInstanceNodes with their WordNodes, and I can also get them...

```
scheme@(guile-user)> (cog-get-atoms 'ReferenceLink)
$4 = ((ReferenceLink
   (WordInstanceNode "telescope.@sentence@013f82af-3f7a-41ba-b4bf-fe180fb91d70_parse_18")
   (WordNode "telescope.")
)
 (ReferenceLink
   (WordInstanceNode "a@sentence@013f82af-3f7a-41ba-b4bf-fe180fb91d70_parse_18")
   (WordNode "a")
)
 (ReferenceLink
   (WordInstanceNode "has@sentence@013f82af-3f7a-41ba-b4bf-fe180fb91d70_parse_18")
   (WordNode "has")
)
 (ReferenceLink
   (WordInstanceNode "telescope.@sentence@013f82af-3f7a-41ba-b4bf-fe180fb91d70_parse_17")
   (WordNode "telescope.")
)
 (ReferenceLink
   (WordInstanceNode "telescope.@sentence@013f82af-3f7a-41ba-b4bf-fe180fb91d70_parse_4")
   (WordNode "telescope.")
)
 (ReferenceLink
   (WordInstanceNode "a@sentence@013f82af-3f7a-41ba-b4bf-fe180fb91d70_parse_17")
   (WordNode "a")
)
 (ReferenceLink
   (WordInstanceNode "has@sentence@013f82af-3f7a-41ba-b4bf-fe180fb91d70_parse_17")
   (WordNode "has")
)
 (ReferenceLink
   (WordInstanceNode "LEFT-WALL@sentence@013f82af-3f7a-41ba-b4bf-fe180fb91d70_parse_17")
   (WordNode "LEFT-WALL")
)
 (ReferenceLink
   (WordInstanceNode "Mom@sentence@013f82af-3f7a-41ba-b4bf-fe180fb91d70_parse_23")
   (WordNode "Mom")
)
 (ReferenceLink
   (WordInstanceNode "has@sentence@013f82af-3f7a-41ba-b4bf-fe180fb91d70_parse_16")
   (WordNode "has")
)

... and more ...
```

**Comment by linas** [comment]
Sorry, I mis-spoke; WordNodes are generated. 

Can you verify the version of link-grammar that you are using? The current version is 5.4.3, but 5.4.1 should work.    There was a change from 5.4.0 which fixed a bug with splitting words with double dashes in the middle of them. For example: `this is--I think--a test`  There were changes regarding double-quotes in 5.4.0 and general changes in punctuation handling in 5.3.16  If you are using 5.3.15 or earlier, that would explain everything:  there were lots of changes, due to my tripping over a large variety of issues such as these.

**Comment by leungmanhin** [comment]
I'm using the latest 5.4.3

**Comment by leungmanhin** [comment]
Yes just checked again, I'm running everything latest... Let me see if I can reproduce this problem on a different computer...

**Comment by linas** [comment]
try the command line clinet, too -- `link-parser any`  will run the "any" language.

**Comment by linas** [comment]
the command-line client will also print the dictionary version -- maybe there are old dictionaries interfering with things. I'm not sure, but I think the opencog.log file will have the version in it.

**Comment by leungmanhin** [comment]
Ohh I guess I found it. It's my `/usr/local/share/link-grammar/any/affix-punc` get corrupted somehow, I replaced it and it's all working now!

**Comment by leungmanhin** [comment]
Thanks for your help. Closing now, it's a user error ;)
