### ISSUE TITLE
Getting Segmentation Fault error while trying execute scheme code using the python api

### ISSUE THREAD

**Issue by Habush** [opencog/opencog#2972]
[5a4f6c2c2ae73d54f1e2b9b2.txt](https://github.com/opencog/opencog/files/1615084/5a4f6c2c2ae73d54f1e2b9b2.txt)
I have MOSES training results in scheme format that I want to import to the atomspace. I am using the OpenCog python api to access the atomsapce and import the results. However, in trying to do so, I am getting "Segmentation fault (core dumped)" error. To demonstrate what I am trying to do, here is a snippet of code I am using.

```
from opencog.scheme_wrapper import scheme_eval, scheme_eval_as

atomspace = scheme_eval_as('(cog-atomspace)')

with open('/path/to/the/result_file', 'r') as fp:
 scm = fp.read()
response = scheme_eval(atomspace, scm) #this is line is the cause of the error.
```
I have attached the file I am reading the results from in this issue

What can be the cause this error?

**Comment by linas** [comment]
It does not core dump for me.  What versions of python, scheme are you using?  Does it still crash if you use guile-2.2 instead of guile-2.0?

what does the stack trace show?

**Comment by Habush** [comment]
I am using `Guile` version 2.2.1 and `Python` 2.7.12 and I still get the error

When using it directly from the python shell, I don't get any stack trace output. However, trying through the **cogserver**'s python shell, I get the following stack trace:

```
[2018-01-09 13:21:10:323] [ERROR] Caught signal 11 (Segmentation fault) on thread 140185633208064
	Stack Trace:
	2: Logger.h:209	  opencog::Logger::Base::~Base()
	3: [0x354b0] ??() ??:0
	4: AtomTable.cc:400	  opencog::AtomTable::add(std::shared_ptr<opencog::Atom>, bool)
	5: shared_ptr_base.h:658	  std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count()
	6: SchemeSmobNew.cc:387	  opencog::SchemeSmob::ss_new_node(scm_unused_struct*, scm_unused_struct*, scm_unused_struct*)
	7: vm-engine.c:787	vm_regular_engine()
	8: vm.c:1258	scm_call_n()
	9: eval.c:502	scm_call_3()
	10: vm-engine.c:787	vm_regular_engine()
	11: vm.c:1258	scm_call_n()
	12: throw.c:139	catch()
	13: SchemeEval.cc:573	  opencog::SchemeEval::do_eval(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
	14: SchemeEval.cc:503	  opencog::SchemeEval::c_wrap_eval(void*)
	15: continuations.c:422	c_body()
	16: vm-engine.c:787	vm_regular_engine()
	17: vm.c:1258	scm_call_n()
	18: throw.c:139	catch()
	19: continuations.c:367	scm_i_with_continuation_barrier()
	20: continuations.c:461	scm_c_with_continuation_barrier()
	21: [0x21c97] ??() ??:0
	22: threads.c:689	with_guile()
	23: [0x1bc62] ??() ??:0
	24: threads.c:710	scm_with_guile()
	25: SchemeEval.cc:474	  opencog::SchemeEval::eval_expr(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
	26: SchemeEval.h:161	eval()
	27: basic_string.h:589	  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)
	28: [0xb2961] ??() ??:0
	29: [0x1e804c] ??() ??:0
	30: [0xa9d99] ??() ??:0
	31: [0x1241e6] ??() ??:0
	32: PythonEval.cc:643	  opencog::PythonEval::execute_string(char const*)
	33: basic_string.h:109	  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Alloc_hider::_Alloc_hider(char*, std::allocator<char> const&)
	34: PythonEval.cc:1412	  opencog::PythonEval::eval_expr_line(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
	35: PythonEval.cc:1342	  opencog::PythonEval::eval_expr(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
	36: GenericShell.cc:460	  opencog::GenericShell::eval_loop()
	37: [0xb8c80] ??() ??:0
	38: [0x76ba] ??() ??:0
	39: clone.S:111	??()

```

**Comment by linas** [comment]
How do you do this? When I try, I get: 
```
with open('/tmp/5a4f6c2c2ae73d54f1e2b9b2.txt', 'r') as fp:
... Python error : ('expected an indented block', ('<string>', 2, 1, '\n')). (/home/linas/src/atomspace-git/opencog/cython/PythonEval.cc:1080)
```

This is due to an old bug in the python shell that no one has bothered to fix (there an issue open for this somewhere).  How are you able to enter this, without hitting this bug first?

**Comment by linas** [comment]
To work around this bug, I created the file:
```
py

print "ollllaa"
from opencog.scheme_wrapper import scheme_eval, scheme_eval_as
atomspace = scheme_eval_as('(cog-atomspace)')
print ("as = ", atomspace)
seem = "(+ 1 1)"
# with open('/tmp/5a4f6c2c2ae73d54f1e2b9b2.txt', 'r') as fp:
#       seem = fp.read()

fp = open('/tmp/5a4f6c2c2ae73d54f1e2b9b2.txt', 'r')
seem = fp.read()

print "it is this " + str(seem)
response = scheme_eval(atomspace, seem)
print "the response is " + str(response)
print "goo-byyyye"
```

and then did a `cat  foo |telnet localhost 17001`
The cogserver stdout then prints:
```
ollllaa
('as = ', <opencog.atomspace.AtomSpace object at 0x7f736f1320b0>)
it is this (EquivalenceLink (stv 1.0 1.0)
 .............. bunch of stuff .......
(ImplicationLink (stv 0.8 1)
    (PredicateNode "-o"))
    (PredicateNode "temp_file_5a4f6ca62ae73d54f1e2b9b3:moses_model_30")

the response is #<Invalid handle>


goo-byyyye
```
and nothing crashes for me...

**Comment by linas** [comment]
By the way, your input file has an incorrect syntax: it says things like
```
(ImplicationLink (stv 0.8 1)
    (PredicateNode "-o"))
    (PredicateNode "temp_file_5a4f6ca62ae73d54f1e2b9b3:moses_model_28")
```
where the parenthesis are misplaced: the ImplicationLink should have two arguments, not one.  It should be this:
```
(ImplicationLink (stv 0.8 1)
    (PredicateNode "-o")
    (PredicateNode "temp_file_5a4f6ca62ae73d54f1e2b9b3:moses_model_28"))
```
Notice the parenthesis

**Comment by linas** [comment]
Hmm. Actualy, it looks like it was printed out-of-order: Based on other parts of the file, it should have printed:
```
(ImplicationLink (stv 0.8 1)
    (PredicateNode "temp_file_5a4f6ca62ae73d54f1e2b9b3:moses_model_28")
    (PredicateNode "-o"))
```
so it looks like there is some moses printing bug as well.

**Comment by linas** [comment]
If I try to manually fix the Implication links, I see that they always come in pairs:
```
(ImplicationLink (stv 0.64 1)
    (PredicateNode "temp_file_5a4f6ca62ae73d54f1e2b9b3:moses_model_13")
    (PredicateNode "-o"))
(ImplicationLink (stv 0.8 1)
    (PredicateNode "-o"))
    (PredicateNode "temp_file_5a4f6ca62ae73d54f1e2b9b3:moses_model_13")
```
This also cannot be right: after manually fixing, they are identical, and just have different truth values.  So it seems there are two distinct moses bugs at work, here.

**Comment by linas** [comment]
Anyway: for your original crash: although I cannot reproduce it, I can kind-of guess at an answer:  it crashes here:  
```
AtomTable.cc:400	  opencog::AtomTable::add(std::shared_ptr<opencog::Atom>
```
If you look at this with GDB, you will probably see a null-pointer dereference: I'm guessing both the atomspace and the atomtable pointer are null. Why would it be null? 

I'm guessing that you are running in a non-standard environment, with the corgserver, but set up in some unusual way (it has to be .. no other way to explain how you avoided the `Python error : ('expected an indented block',` error.)  In this environment, I am guessing that the line `atomspace = scheme_eval_as('(cog-atomspace)')`   is somehow lost by the time that you go to use it:   so that if you did
```
print ("the as is this = ", atomspace)
response = scheme_eval(atomspace, seem)
```
you will probably get junk, or a null pointer from the print statement, resulting in a crash in the later `scheme_eval`

**Comment by linas** [comment]
In addition, the python bindings are also broken.  If I simply run this
```
from opencog.scheme_wrapper import scheme_eval, scheme_eval_as
atomspace = scheme_eval_as('(cog-atomspace)')
print ("as = ", atomspace)
seem = '(ConceptNode "foo")'
print "it is this " + str(seem)
response = scheme_eval(atomspace, seem)
print "the response is " + str(response)
print "goo-byyyye"
```
then the response is always:
```
the response is #<Invalid handle>
```
 which clearly seems wrong to me.  So I would say that there are maybe four different bugs here:
1) the crash  (null pointer deref)
2) the misbehaving PyShell in the cogserver
3) bad moses printing
4) the `scheme_eval` function in python is mis-handling return values.

You'll need to do some work to fix all these. Pull requests anticipated!

**Comment by Habush** [comment]
> I'm guessing that you are running in a non-standard environment, with the cogserver, but set up in some unusual way (it has to be .. no other way to explain how you avoided the Python error : ('expected an indented block', error.) 

I followed the installation guides on the **README** to install all the components(Opencog, Atomspace, Cogutils).  Hence, I don't know how my environment is a different.
But when I run it on the German server, I don't get the `Segmentation fault` error, I get the same response as yours without getting the `Python error : ('expected an indented block', error.)` error. That is odd. Is it machine specific?

Btw, using an `AtomSpace` works fine and doesn't bring up the issue. The issue is raised only when using `cog-atomspace`.

**Comment by linas** [comment]
> Is it machine specific?

It should not be. Your anecdotal evidence is interesting, but the standard way of reporting bugs like this is to be precise about which operating system, which version of python, gcc, guile, etc is being used. 

The `Segmentation fault`  and the `indented block` are real bugs, and I rather expect that you or one or more people at iCog Labs will work hard to understand these problems, and come up with fixes for them.  Don't expect me to do this for you.

The `opencog.atomspace.AtomSpace` vs `cog-atomspace` is also a real bug.  The way that python is handling atomspaces is kind of bizarre and broken, it has always been a problem, and has been hacked around, but its never been well-designed.   Again - this is a real bug, and someone at iCog Labs needs to deal with this.  Talk this over with whomever is in charge there.

Please note that these are potentially rather complex problems, and may take a while to solve. Whomever does work to solve this will become experts in OpenCog.  Most corporations require their employees to spend half-a-year or a year fixing bugs, so that they can learn the system.  This is done *before* doing application development.  iCog Labs should be operating like this as well.

**Comment by mjsduncan** [comment]
i think part of the problem here is that the "standard system" has become indeterminate.  i'm also getting the segfault using current pulls of the opencog stack on current ubuntu 16.04.  i have the impression that neither you or nils are actually using this for development.  linus, as a start, can you give us a procedure to determine our system dependencies in enough detail so we can compare them to yours?  it's not your job to fix this but you and nil as the lead developers are de facto determining what the base system is that everyone else is working from and it's not clear to me any more what that is.  there is also more development being done on docker containers and if the "standard system" is working differently between native and docker setups we should sort that out sooner rather than later, no?

**Comment by ngeiswei** [comment]
@mjsduncan I'm running Ubuntu 17.10, Debian Jessie and Fedora 27, all seem to support OpenCog just fine. However I don't use Python bindings, neither the cogserver. I could take a look at it on Monday if that helps.

**Comment by mjsduncan** [comment]
the mozi infrastructure isn't using the cogserver anymore.  i suspect the
problem is the related to the python REST interface, which was supposed to
be rewritten in c++ and probably hasn't been touched since well before
linus upgraded the atomspace publisher module code last month

**Comment by mjsduncan** [comment]
the opencog/docker build still uses ubuntu 14.04, though there are at least
2 versions of octool for 16.04 floating around.  since 14.04 is now 2 years
past due shouldn't it be officially phased out by now?  also most of my
time-wasting headaches getting things to work seem to revolve around
python, including discrepancies in unit tests.  would setting up a standard
python environment for opencog be worthwhile?

**Comment by linas** [comment]
> "standard system" 

Opencog should run on the various ubuntu's, redhat, and debian.  There's no reason it should not.  There are bugs. Someone needs to fix them. 

There used to be a buildbot that automated testing, but the buildbot is broken. Someone should fix that too, and re-enable testing on ubuntu 14.04, 16.04, redhat and debian.   The ideal person to fix this would be someone junior, a new hire.

We need to support 14.04 for the robots, since the robots use ROS indigo, which runs only on 14.04.  If/when the robots get ported to a newer version of ROS, then support for 14.04 can be dropped.

**Comment by linas** [comment]
> most of my time-wasting headaches getting things to work seem to revolve around python, 

That's right!  Python has been neglected for years!  There's maybe a dozen bugs open against it, just moldering and getting old.   Someone from iCog Labs piped up on the mailing list, said they'd work on python, but then I have not heard another peep. I think they did not realize that python is actually cython under the covers, and they don't know how to deal with that.  Whatever. If you want python, we would need to assign someone full-time to crawl through the bug back-log and fix things.  I'm guessing wildly that there are 3-6 months worth of python bugs in the code.

**Comment by linas** [comment]
Five python bugs here:  https://github.com/opencog/opencog/labels/python 
Three python bugs here: https://github.com/opencog/atomspace/labels/python

So maybe that's not so bad - maybe just one months worth of work!?

**Comment by edguy3** [comment]
I, too, struggled with builds on 16.04 so I’m setting up a ‘build/test bot’ at the moment; assuming the semester startup

activities don’t interfere too much, I ought to publish some results in a few days. 

 

/ed

 

=====================

Edward T Guy, III, Ph.D.
Cen.ai

Chief Technology Officer

+1 908 400 0094

**Comment by edguy3** [comment]
Jenkins status as of today’s changes: 

OpenCOG_U1404_Opencog:	76% tests passed, 6 tests failed out of 25

OpenCOG_U1604_Opencog : 	72% tests passed, 7 tests failed out of 25
OpenCOG_U1604_AtomSpace: 	98% tests passed, 2 tests failed out of 111
OpenCOG_U1604_Moses:	100% tests passed, 0 tests failed out of 35


See https://github.com/edguy3/CenStatus for the full status list 

/ed

=====================
Edward T Guy, III, Ph.D.
Cen.ai
Chief Technology Officer
+1 908 400 0094

**Comment by linas** [comment]
I'm looking into this bug now. For some reason, cython never noticed that it had an invalid atomspace.

**Comment by linas** [comment]
I think I fixed this bug in https://github.com/opencog/atomspace/pull/1518  -- scheme was not fully initialized by the time that python started running.  Now it is.

**Comment by linas** [comment]
The moses printing bug  mentioned above remains unfixed.  Someone needs to fix that, or your biochemistry won't work.
