### ISSUE TITLE
guile readline prerequisites not covered by octool

### ISSUE THREAD

**Issue by fm444fm** [opencog/opencog#3041]
As I found out after a lot of tinkering, the current installation of opencog (following the wiki guides on how to build and using octool for dependencies, github cloning, building....) produces problems trying to install guile and in particular among other things (including a ELF signature missing error...) misses the compilation of support for readline module in guile.
I installed the latest guile by myself (without using "octool -g") but still something was missing.
In the end discovered that one of the prerequisites "package libreadline6-dev" is not installed by octool.
Suggesting hence here with this message to add that prerequisite in order to remove this problem.
Best regards.

**Comment by AmeBel** [comment]
Fixed the readline issue with octool by https://github.com/opencog/ocpkg/pull/105. 

Would you please provide more details on what you referred to us `ELF signature missing error`?

**Comment by mjsduncan** [comment]
i think i got the same error when i built guile 2.2.2 by hand for ubuntu 16.04 but there is now a package for 2.2.3 which doesn't have that issue.

**Comment by AmeBel** [comment]
@mjsduncan what do you mean by package?

**Comment by mjsduncan** [comment]
debian package for ubuntu

**Comment by linas** [comment]
Yes. ubnutu 17..10 and probably 17.04 and maybe even 16.10 and 16.04 might actually be modern enough to have a version of guile-2.2 to work well with opencog.  The biggest issue with using guile was having Relex send it very long strings (5-10 or 20 megabytes of ascii/utf8 scheme code creating atoms to represent sentence parses) -- this is now gone.

Basically, there were 6 or more different guile bugs that got triggered by these giant strings - threading bugs, crashes in the guile compiler, blowing out RAM due to infrequent garbage collection, slowdowns from compiling large strings, crashes in UTF8 processing .. etc.  The guile folks fixed most of these in guile-2.2, and now they also mostly won't get triggered because we no longer send these giant strings via tcp/ip socket to opencog (cause we don't use the relex server any more)

**Comment by linas** [comment]
To summarize: building guile from source is probably not necessary, thanks to a a modern guile being available by default, in many distros.

**Comment by AmeBel** [comment]
@mjsduncan 17.10 doesn't have guile-2.2. 18.04 that is to be release at the end of this month does https://packages.ubuntu.com/search?suite=all&arch=any&searchon=names&keywords=guile-2.2 . If there is any PPA that you know of let me know.

Debian testing does have guile-2.2 https://packages.debian.org/search?suite=all&arch=any&searchon=names&keywords=guile-2.2

@linas If the core team agrees to use 18.04 as reference os, then building from source can be avoided. The other option is backporting the package to 16.04 on our ppa https://launchpad.net/~opencog-dev/+archive/ubuntu/ppa

**Comment by linas** [comment]
Hanson Robotics has been preparing to make the jump from 14.04 to 16.04 but perhaps 18.04 makes more sense, since they haven't made the jump yet.

**Comment by fm444fm** [comment]
> Would you please provide more details on what you referred to us ELF signature missing error?

I think it is caused by ldconfig, which is called during configuration and after building. It complains saying: "/sbin/ldconfig.real: /usr/local/lib/libguile-2.2.so.1.3.0-gdb.scm is not an ELF file - it has the wrong magic bytes at the start.

**Comment by fm444fm** [comment]
Another dependency probably missing: when I try to load module libatomspacepublishermodule.so it complains it cannot open shared object libjson_spirit.so

**Comment by AmeBel** [comment]
@fm444fm what are the steps for reproducing your error? Couldn't reproduce it when loading the module.

@Dagiopia where do you have the debian packaging files?

**Comment by AmeBel** [comment]
@fm444fm with regards to the ELF , it is required for debugging using gdb. For details see https://www.gnu.org/software/guile/manual/guile.html#GDB-Support

**Comment by Dagiopia** [comment]
@AmeBel for the time being a script downloads them from here http://144.76.153.5/opencog/
@fm444fm I'm not sure about this but ldconfig searches for libs based on the .so extension in specific dirs like /lib /usr/lib and anything specified in ld.so.conf and since it checks for the filetype from the header if it's an elf or different type, it finds that libguile-2.2.so.1.3.0-gdb.scm has the .so extension but is still an scm file so the elf-check fails 
it's not a bad thing, it's just annoying... you can move the file to gdb's autoload /usr/share/gdb/auto-load/usr/lib so that gdb can use it (amen explained its use)

**Comment by AmeBel** [comment]
@fm444fm what is your command for starting the cogserver?

**Comment by fm444fm** [comment]
no, json_spirit not installed anywhere in /usr/local/

I start using cogserver -c /usr/local/etc/opencog.conf, which I edited according to wiki suggestions and adding STORAGE definitions and uncommenting libatomspacepublishermodule

**Comment by fm444fm** [comment]
manually copying opencog/build/lib/json_spirit/libjson_spirit.so to /usr/local/lib allows the module to be loaded. So maybe the make install misses something to allow the correct installation of that library...

Anyway this still did not help me to continue on my study of the wiki tutorials. I thought that module would have enabled me to go through "https://wiki.opencog.org/w/Using_a_Backing_Store" allowing the "sql-store" command as detailed there, but it appears this is not the case. 

I saw the notes on "telnet being broken" and sql-store only available via guile, so I guess the sql-store and sql-open mentioned in that wiki page are still broken, even if the second "note" seemed to affirm it was still possible to make it work. I thought it was not working to me because of the libatomspacepublishermodule...

**Comment by fm444fm** [comment]
Running make tests and make test in opencog results in:

85% tests passed, 3 tests failed out of 20

Total Test time (real) = 481.09 sec

The following tests FAILED:
          6 - AtomOcTreeUTest (SEGFAULT)
          7 - TimeSpaceAtomUTest (SEGFAULT)
         11 - PLNRulesUTest (Failed)
Errors while running CTest
CMakeFiles/test.dir/build.make:57: recipe for target 'CMakeFiles/test' failed

**Comment by linas** [comment]
The wiki page for the sql stuff is wildly out of date.  I believe that the README in the source code is correct and up to date. sql-open, sql-store work fine; I use them regularly.

The three failing unit tests are currently considered to be "normal".

The atomspacepublisher module should either static-link to the json-spirit library, or it should install it.  I believe that a static link would be better, for this particular case, because nothing else in opencog needs or wants the json-spirit library.

**Comment by mjsduncan** [comment]
yes, i have successfully used
github/opencog/atomspace/opencog/persist/sql/README.md to get pgsql backing
store working, the installation steps start halfway through the document.
i don't use obdc because it's extra work and according to linus
significantly slower.  it gets built and used automatically unless you
remove the obdc related packages.  maybe linus can post his copy of the
updated config files for postgres server since working through the
recommended changes is lengthy (tho informative).

**Comment by linas** [comment]
Hmm. 

First, someone really needs to update the wiki page. I'm trying to figure out how to delegate that kind of work so I don't have to do everything.

Second, if there are actual remaining issues with sql, and how it works/doesn't work, that should get handled in a distinct bug report, instead of piling on here. This has become a free-for-all on various issues, which makes it impossible to track and fix any of them, because its no longer clear what the actual problem is any more.

**Comment by mjsduncan** [comment]
linus, the problem with delegating work on this is that since you developed the code, you are the only person who really understands it.
