### ISSUE TITLE
MathUTest fails with gcc-4.7

### ISSUE THREAD

**Issue by linas** [opencog/opencog#309]
MathUTest  pass/fail seems to depend on some very subtle float-point rounding issues; a minor change in rounding causes the test to blow up.  I debugged a little and here's what I found:

rectangles are added and removed from SuperEntity, and then the overall geometry is recomputed in SuperEntity::rebuild()  This uses the function rectangle.isInside() repeatedly to test if geometries intersect. 

The problem seems to be that the geometries neither intersect, nor don't intersect: they just touch. So the tiniest shift in geometry, a change in the last bit of a floating-pint number, will cause the Rectangle::isInside() to go from true to false.  This changes how SuperEntity::rebuild() responds, and thus, causes MathUTest to bomb out.

Figuring out how to fix this will require understanding what SuperEntity is and what it does ...

**Comment by brett79** [comment]
SuperEntity provides behaviour to gather the outside 2D perimeter of a number of overlapping entities. Any internal edges are 'hidden'.This could be useful if a lot of objects are overlapping and you wish to navigate around them. The MathUTest was checking for the edges to be in a specific order. Order is not enforced within the existing code, and entities are stored in a non-ordered hash map. Suggested fix is to check for the correct edges, and ignore the order they are presented.
While reviewing the code, I noticed an extra edge being deleted due to some midpoint checking, fix should be to check either end of the edge.

**Comment by linas** [comment]
Hi, Thanks for the patch; I merged because it looked reasonable. If you understand, even partly, what this code does, could you added an explanation, either to the .cc or the .h file, or possibly create a wiki page for it?  My general impression is that everything in the 'spatial' directory is under-documented, and no one has a very clear idea of what it is or what it does.  (Well, I don't)

**Comment by AmeBel** [comment]
The test is passing,
buildbot.opencog.org:8010/builders/opencog_master_trusty/builds/70/steps/test/logs/stdio
