### ISSUE TITLE
PatternMinerUTest build fails for ubuntu 17.10 with newer libboost v1.62

### ISSUE THREAD

**Issue by mjsduncan** [opencog/opencog#3101]
is there a reason libboost v1.58 is required?  if so it should be mentioned in the README.
ubuntu 17.10 uses v1.62.0 and ubuntu 18.04 uses v1.65.1
```
[ 86%] Linking CXX executable PatternMinerUTest
/usr/bin/x86_64-linux-gnu-ld: warning: libboost_system.so.1.58.0, needed by /usr/local/lib/libcpprest.so, not found (try using -rpath or -rpath-link)
/usr/bin/x86_64-linux-gnu-ld: warning: libboost_thread.so.1.58.0, needed by /usr/local/lib/libcpprest.so, not found (try using -rpath or -rpath-link)
/usr/local/lib/libcpprest.so: undefined reference to `boost::this_thread::yield()'
```

**Comment by linas** [comment]
Mike, the fact that cpprest is located here: `/usr/local/lib/libcpprest.so` means that you installed it there, since Ubuntu (nor Debian, RedHat, any standard linux system) never-ever installs anything in `/usr/local` -- so, don't know how you created, copied, got that version of cpprest.so, but it was built against version 1.58 and so it needs that.  

The solution is to remove your private copy, and use the system standard one. Don't forget to remove your private header files, too, in `/usr/local/include`  The system-standard cpprest can be found and installed like so:

```
$ apt-cache search cpprest
libcpprest-dev - Development files for Casablanca
libcpprest-doc - Reference manual for Casablanca
libcpprest2.9 - Shared library for Casablanca
You have new mail
$ sudo apt-get install libcpprest-dev
[sudo] password for linas: 
```

**Comment by mjsduncan** [comment]
this is still in the README:

CppREST

    C++ HTTP RESTful interfaces Used by the Pattern miner for distributed processing (this will be replaced by gearman in future releases).
wget https://github.com/Microsoft/cpprestsdk/archive/v2.9.0.tar.gz

**Comment by linas** [comment]
I just updated the README to say `apt-get` instead.
