### ISSUE TITLE
Tokenizer breaks MST-parser

### ISSUE THREAD

**Issue by glicerico** [opencog/opencog#3212]
During the MST-parse part of the NLP learn pipeline, the tokenizer removes spaces between dots and dashes:
https://github.com/opencog/opencog/blob/60fec1c292b89d913b3cd3200c3e76dd0ee0a0b4/opencog/nlp/learn/scm/mst-parser.scm#L179
The tokenizer in LG parser in "any" mode doesn't include this feature. This causes lines in the text like ". . . . . ." to be transformed into "......" and the MST-parse fails because a word composed of six consecutive dots wasn't counted during the pair-counting phase.

**Comment by glicerico** [comment]
Proposed solution in PR: https://github.com/opencog/opencog/pull/3213

**Comment by glicerico** [comment]
Sorry, I forgot to include how to reproduce this problem. If you use a simple file with three lines like the following:

" mom is a human.

  . . . . . . .

  dad is a human."

And do the whole pair-counting, mutual information, and mst-parsing processes specified in in nlp/learn/README.md, you'll see an error when mst-parsing the second line of the example file ". . . . . . ."

**Comment by linas** [comment]
Sorry, I don't understand the problem.  If all text goes throuogh the tokenizer, how can some text sometimes not go through the tokenizer?

**Comment by linas** [comment]
Oh, I see -- you actually had a string of white-space separated dots in the input.

**Comment by glicerico** [comment]
There are two tokenizers in the NLP pipeline: the LG tokenizer used while pair-counting with LG "any" mode, and the tokenizer (included in mst-parses.scm) used during mst-parsing. This issue is reporting a situation when those tokenizers treat a sentence differently.
Yes, the sentence (coming from a Gutenberg book) is just a number of dots separated by spaces.

**Comment by linas** [comment]
The tokenizer in LG is very complex: it creates a graph of possible parallel paths through a sentence.  The canonical example is "seasand beach" which could be "seas and beach", "sea sand beach" or (after typo correction) "seasoned beech" or simply "(unknown word) beach"  -- 

There's no particularly easy way to port this to opencog; the MST side of things does not know about word-graphs, even if it was ported.  I was hoping to defer action on this until work on morphology begins. 

In the meanwhile, here's an easy hack: instead of inserting spaces, insert some other mark, e.g. 0x2  Then remove the 0x2 then convert all remaining 0x2 into spaces as the final step. This performs tokenization, without damaging the spaces in the original text.  Since the original text is unlikely to contain 0x2, that won't be damaged either.

**Comment by glicerico** [comment]
Thanks for the suggestion, sounds like a reasonable workaround.
Does the LG tokenizer in "any" language (the one used for the MST-pipeline) also explore these parallel paths in the sentence?
If that's the case, wouldn't it be more consistent to use the LG tokenizer (getting only one parse, just to get the tokenization) at the beginning of the MST-parse process? Perhaps that adds too much computational complexity?

**Comment by linas** [comment]
The LG tokenizer does not have any externally-visible API. Perhaps it could, but adding this is non-trivial.  This has actually been discussed a lot in multiple github issues on the LG repo, but we've never really been able to think of an API for it.

**Comment by linas** [comment]
Closing; the code base is now in a different repo, and what is left of the issue seems like an enhancement request.
