### ISSUE TITLE
ImportError: No module named 'opencog.atomspace'

### ISSUE THREAD

**Issue by linas** [opencog/opencog#3528]
Recently, not sure when, I started getting the error
```
ImportError: No module named 'opencog.atomspace'
```
when starting the cogserver.  I do NOT have the `PYTHONPATH` set; this is usually not needed.

I start the cogserver like so:
```
$ guile
(use-modules (opencog) (opencog cogserver))
(start-cogserver)
```
which used to work without error. It still seems to work, except now the error is printed, and also, I assume, python does not work...

**Comment by ferrouswheel** [comment]
Perhaps 29e6159224 is related?

**Comment by linas** [comment]
On my system, the python module is located here: `/usr/local//lib/python3/dist-packages/opencog/atomspace.so`  and given the recent changes to the CMakefile install paths, I assumed that everyone's python would end up there, or some similar location.  It's been getting installed either into `dist-packages` or `site-packages` for years, now, so  the removed paths have been invalid for at least that long...

**Comment by vsbogd** [comment]
It is duplicate of https://github.com/opencog/atomspace/issues/1782.
Root cause is that Ubuntu `python` version returns unusual path when `get_python_lib()` is called with non-default prefix (`/usr/local` for instance). See https://bugs.launchpad.net/ubuntu/+source/python3-defaults/+bug/1814653
Workarounds are using python built from source or using `PYTHONPATH` which includes `/usr/local`

**Comment by linas** [comment]
Ah. I get that error on Debian; I don't get it on Ubuntu.  Anyway, I got confused; I thought this was due to the cogserver python module, not the python python module, so, yes it is a duplicate of #1782
