### ISSUE TITLE
In procedure module-lookup: Unbound variable: opencog-ext-path-ure

### ISSUE THREAD

**Issue by StrangeTcy** [opencog/opencog#3577]
Trying to run [`run-chatbot.scm`](https://github.com/opencog/opencog/blob/master/opencog/nlp/chatbot/run-chatbot.scm) by opening a `guile` prompt and pasting lines one at a time  fails at line 11.
The exact output looks like this:
```
guile
GNU Guile 2.2.4
Copyright (C) 1995-2017 Free Software Foundation, Inc.

Guile comes with ABSOLUTELY NO WARRANTY; for details type `,show w'.
This program is free software, and you are welcome to redistribute it
under certain conditions; type `,show c' for details.

Enter `,help' for help.
scheme@(guile-user)> (use-modules (ice-9 readline))
(activate-readline)scheme@(guile-user)> 
scheme@(guile-user)> ; Stuff actually needed to get the chatbot running...
(use-modules (opencog) (opencog cogserver))
scheme@(guile-user)> (use-modules (opencog nlp) (opencog nlp chatbot))
While compiling expression:
In procedure module-lookup: Unbound variable: opencog-ext-path-ure
scheme@(guile-user)> 
```

ETA: `guile -l run-chatbot.scm` fails in a slightly different way:
```
;;; In procedure module-lookup: Unbound variable: opencog-ext-path-ure
Backtrace:
           1 (primitive-load-path "opencog/nlp/relex2logic/loader/ge…")
In opencog/nlp/relex2logic/loader/gen-r2l-en-rulebase.scm:
      5:0  0 (_)

opencog/nlp/relex2logic/loader/gen-r2l-en-rulebase.scm:5:0: In procedure module-lookup: Unbound variable: ure-define-rbs
```

**Comment by ngeiswei** [comment]
@StrangeTcy, do you know if that problem appeared since I split the ure from the atomspace?

**Comment by ngeiswei** [comment]
@StrangeTcy, I cannot reproduce your problem. You probably need to purge you system from previous installations.

To purge my system from opencog I use the following

https://github.com/ngeiswei/ocbld

```
./ocbld uninstall
```

**Comment by StrangeTcy** [comment]
Well, several clean-ups & re-compilations later it finally works.

**Comment by TheScott463** [comment]
Has anyone begun to integrate this breakthrough?This will have widespread application. See this paper:https://arxiv.org/abs/1805.07470Paper can be downloaded.Seems like a good addition.Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Maxim Smirnov <notifications@github.com> Date: 7/15/19  3:30 AM  (GMT-08:00) To: opencog/opencog <opencog@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [opencog/opencog] In procedure module-lookup: Unbound variable: opencog-ext-path-ure (#3577) Closed #3577.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/opencog/opencog/issues/3577?email_source=notifications\u0026email_token=ALGPUNWHZ7VL6OAPQLG3NWDP7RGTRA5CNFSM4ICECXV2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOSP3QUGY#event-2482440731",
"url": "https://github.com/opencog/opencog/issues/3577?email_source=notifications\u0026email_token=ALGPUNWHZ7VL6OAPQLG3NWDP7RGTRA5CNFSM4ICECXV2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOSP3QUGY#event-2482440731",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ngeiswei** [comment]
Excellent suggestion, I've actually been thinking of using the rubik's cube as test case for inference control meta-learning, with a sequence of problems with increasing difficulty by controlling the distance from random to solved, wondering if OpenCog could learn the algo. Looks like it's doable, awesome!

**Comment by TheScott463** [comment]
Let me know if I can help. I'm a "noob" with this effort. I'd appreciate any guidance.I am a Computer Scientist and application engineer.Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Nil Geisweiller <notifications@github.com> Date: 7/15/19  8:50 AM  (GMT-08:00) To: opencog/opencog <opencog@noreply.github.com> Cc: Scott Cole <colepossible@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [opencog/opencog] In procedure module-lookup: Unbound variable: opencog-ext-path-ure (#3577) Excellent suggestion, I've actually been thinking of using the rubik's cube as test case for inference control meta-learning, with a sequence of problems with increasing difficulty by controlling the distance from random to solved, wondering if OpenCog could learn the algo. Looks like it's doable, awesome!

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/opencog/opencog/issues/3577?email_source=notifications\u0026email_token=ALGPUNWDFUSXJXAZTAGIJKLP7SMFLA5CNFSM4ICECXV2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZ6D4YA#issuecomment-511458912",
"url": "https://github.com/opencog/opencog/issues/3577?email_source=notifications\u0026email_token=ALGPUNWDFUSXJXAZTAGIJKLP7SMFLA5CNFSM4ICECXV2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZ6D4YA#issuecomment-511458912",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ngeiswei** [comment]
Sure, I'll probably get back to inference control meta-learning in 2 months or so, then I'll look deeply into it. Meanwhile if you wish to look into inference control meta-learning (not that it's only way to translate that to opencog, and maybe it's actually a bad way but I want to try) you can look into

https://github.com/opencog/opencog/tree/master/examples/pln/inference-control-learning
https://blog.singularitynet.io/introspective-reasoning-within-the-opencog-framework-1bc7e182827
https://blog.opencog.org/2017/10/14/inference-meta-learning-part-i/

Side note on the communication medium, you probably want to use the opencog mailing list https://groups.google.com/forum/#!forum/opencog which is for more general discussions instead of github which is more narrow/tech communication. No problem abusing it once in a while of course.

**Comment by linas** [comment]
it would be nice if we didn't spam bug reports with unrelated conversation...
