### ISSUE TITLE
No code for module PLN

### ISSUE THREAD

**Issue by Ophien** [opencog/opencog#3583]
Trying to load the PLN module but it does not exist.

Receiving:
```
While compiling expression:
no code for module (opencog pln)
```

How to reproduce:
```
Install opencog/cogutil
Install opencog/atomspace
Install opencog/opencog
Install opencog/ure
```

Run guile and execute 
```
(use-modules (opencog pln))
```

**Comment by ngeiswei** [comment]
You need to install the `ure` before `opencog` otherwise `pln` is disabled.

**Comment by Ophien** [comment]
Thx, It worked, but now I'm receiving the following.

```
Backtrace:In ice-9/boot-9.scm:   
222:29 19 map1 opencog logger opencog exec # nlp # …   
222:29 18 map1 opencog exec opencog nlp opencog … …   
222:29 17 map1 opencog nlp opencog nlp chatbot # … …   
222:29 16 map1 opencog nlp chatbot opencog nlp sureal …   
222:29 15 map1 opencog nlp sureal opencog openpsi # …  
222:29 14 map1 opencog openpsi opencog pln # # #   
222:29 13 map1 opencog pln opencog rule-engine # #   
222:17 12 map1 opencog rule-engine opencog ghost  
2788:17 11 resolve-interface opencog rule-engine #:select _ # _ …  
2714:10 10 _ opencog rule-engine _ _ #:ensure _  
2982:16  9 try-module-autoload _ _   
2312:4  8 save-module-excursion #<procedure 7f0ec480f390 at ice-…>  
3002:22  7 _In unknown file:           
6 primitive-load-path "opencog/rule-engine" #<procedure …>In ice-9/eval.scm:   
196:35  5 _ #f   196:35  4 _ #f   
223:20  3 proc #<directory opencog rule-engine 7f0ec6583aa0>In unknown file:           
2 %resolve-variable 7 . opencog-ext-path-exec #<direct…>In ice-9/boot-9.scm:   
751:25  1 dispatch-exception 0 unbound-variable #f "Unbound …" …In unknown file:           
0 apply-smob/1 #<catch-closure 7f0ed5707180> # #f "Unbo…" …
ERROR: In procedure apply-smob/1:Unbound variable: opencog-ext-path-execABORT: unbound-variable
```

**Comment by linas** [comment]
`opencog-ext-path-exec` was added last week by @ferrouswheel  ... it is defined in the module `(opencog as-config)` which ... Hmm

Did you do the git-pull and make and make install all on the same day? Because maybe you missed last-weeks changes.

**Comment by Ophien** [comment]
Tried to do everything from scratch a couple of minutes ago and currently trying at this message timestamp.

**Comment by linas** [comment]
@ngeiswei  The last error says `rule-engine` ... does URE include the needed load of `(opencopg as-config)` in it?

Also, on my system, `(as-config)` gets installed, but the installed file has paths that reference the build directory, which may no longer be there. .. referencing the source dir or the build dir in an installed file is .. dangerous.

@Ophien several remarks:

1) normally opencog is not quite this unstable, but we're embarked on a cleanup

2) this kind of failure is real typical of systems programming.  Something like 90% of all systems bugs look like this.

3) Debugging it is always .. a challenge. You have to poke around and find what should have been included (well, I told you that already, so that part is done) and then figure out why it is not included (that's for you .. or someone to do. I suggest you trying it, because, well, this is a skill that generic system programmers all need to have...)

Something somewhere, maybe in the URE, is not including `as-config` the way that other parts are. On top of which the paths in `as-config` are broken...

**Comment by Ophien** [comment]
Duly noted. I'm trying to check for that missing include.

**Comment by ferrouswheel** [comment]
`as-config` has both systems dirs and build dirs in it. The symbol `in-build-dir` controls which set of paths is used at runtime, and should be set to false for the installed version of `as-config.scm`.

We could make cmake create completely separate `as-config` files, to get rid of this flag.

However the flag `in-build-dir` is also optionally used to panic if atomspace tests are running and are somehow loading scheme modules from the install dir instead of the build dir. This check saved me losing my sanity while trying to untangle the library path munging we used to do.

Looking at ure's `opencog/scm/opencog/rule-engine.scm`, the problem is that
`opencog-ext-path-exec` should be `opencog-ext-path-ure`.

**Comment by ferrouswheel** [comment]
I hadn't the changed the symbol name, and Nil copied it verbatim to URE here: https://github.com/opencog/atomspace/pull/2265/files#diff-6de76cea23de75464d1ea28c1750ef4aL8

I guess it didn't cause any test failures as the module is deprecated.

@Ophien Should probably update the code to use `ure` instead of `rule-engine`.

I will make a PR for URE shortly.

**Comment by Ophien** [comment]
It worked perfectly.
