### ISSUE TITLE
LgConnector is always interpreted as a node in Guile

### ISSUE THREAD

**Issue by leungmanhin** [opencog/opencog#3662]
As seen in Guile shell:

```Scheme
scheme@(guile-user)> (use-modules (opencog) (opencog nlp))
scheme@(guile-user)> (LgConnector)
$1 = (LgConnectorNode)

scheme@(guile-user)> (LgConnector (LgConnectorNode "Wa") (LgConnDirNode "-"))
$2 = (LgConnectorNode
  (LgConnectorNode "Wa")
  (LgConnDirNode "-"))

scheme@(guile-user)> (cog-get-atoms 'LgConnector)
$3 = ((LgConnectorNode
  (LgConnectorNode "Wa")
  (LgConnDirNode "-"))
 (LgConnectorNode)
 (LgConnectorNode "Wa")
)
scheme@(guile-user)> (cog-get-atoms 'LgConnectorNode)
$4 = ((LgConnectorNode
  (LgConnectorNode "Wa")
  (LgConnDirNode "-"))
 (LgConnectorNode)
 (LgConnectorNode "Wa")
)
```

**Comment by linas** [comment]
Whoops. There should not be both a `LgConnectorNode` and an `LgConnectorLink` ...

**Comment by linas** [comment]
This appears to be a very old bug (at least 6 years old!?). I am changing every occurence of `LgConnectorNode` to `LgConnNode`, so that it matches the naming scheme for all the other `LgConn` types.

**Comment by linas** [comment]
fixed in #3669

**Comment by leungmanhin** [comment]
Thanks @linas

**Comment by linas** [comment]
BTW, since you seem to be paying attention, I may as well say it here: there is a major change to how opencog is built: you now need to git clone, build and install https://githib.com/opencog/lg-atomese first. It splits out the link-grammar part.  Let others know, if they care.

All that is left in the main opencog repo are the chatbots, and pretty much nothing else.  Other than that, everything should work (or not work, as the case may be) just as before.
