### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by TerrePorter** [opencog/opencog#3671]
hello.

using the instructions from https://wiki.opencog.org/w/Building_OpenCog#Building for Ubuntu. 

I ran into a snag, 
```
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://cli-assets.heroku.com/apt ./ InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6DB5542C356545CF
```
was the first error, but i was able to fix that one by doing, 
```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6DB5542C356545CF
```

However i am at a loss how to fix these errors
```
E: Failed to fetch https://dl.bintray.com/rabbitmq-erlang/debian/dists/bionic/InRelease  403  Forbidden [IP: 34.209.176.102 443]
E: The repository 'https://dl.bintray.com/rabbitmq-erlang/debian bionic InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://dl.bintray.com/rabbitmq/debian/dists/bionic/InRelease  403  Forbidden [IP: 34.209.176.102 443]
E: The repository 'https://dl.bintray.com/rabbitmq/debian bionic InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'http://apt.postgresql.org/pub/repos/apt focal-pgdg InRelease' doesn't support architecture 'i386'
```
The first one is to a website that just says forbidden on all the pages. 

any ideas?

**Comment by linas** [comment]
I think octool needs to be updated.  Here's what I think is happening:

bionic is Ubuntu 18.04.5 LTS (Bionic Beaver) so that's fairly old -- it would be better to use the current LTS (long term support) 20.04 aka "Focal Fossa" 

The octool asks Ubuntu where to download from, and thers a list of 500 or more servers thatoffer downloads ... one is randomly selected. I guess that bintray.com is on that list, but that its .. not working.  My guess: run octool again, and maybe it will pick a different random server.

Even if the above is fixed, you will run in into another problem: very recently, the `opencog` repo depends on the `lg-atomese` repo and octool hasn't been updated to install that. 

The third issue is that, at this time, the main opencog repo itself is no longer all that interesting -- it has some aging chatbots in it, and .. that's all. All the interesting stuff is going on in other git repos. It all depends on what you want to do .. best would be to write to the mailing list and introduce yourself, explain what you want to do ...

**Comment by fenderrex** [comment]
> 
> Even if the above is fixed, you will run in into another problem: very recently, the `opencog` repo depends on the `lg-atomese` repo and octool hasn't been updated to install that. 
So what you're telling me is that version control is absolutely useless when code is literally sourced from a version control system

**Comment by TerrePorter** [comment]
@linas So opencog is just a publicity stunt and doesnt really work. I was looking to make a chat bot and assistant, just for fun. thanks for reading. i will see what else i can find.

**Comment by linas** [comment]
Guys, please don't come here to heave insults and throw bombs. The stuff here is software, just like any other software. It needs to be maintained and kept up to date. Right now, there is only a part-time maintainer for `octool` who is busy working on other things. I invite you to submit a patch that updates it to the latest ubuntu, and installs this one new dependency. It can't be hard. Lookin' at you @fenderrex 

As to @TerrePorter no it's not a publicity stunt. It's a research project, and much has been discovered and learned.The integration of natural language with common-sense reasoning is not a priority at this time; we are working on other things. "We" is a disparate group of people with diverse interests. Some people are working on biochemistry solvers integrated with logic inference (see the MOZI project -- https://github.com/mozi-ai/ ).  Other people are trying to mash up common-sense reasoning with a minecraft world (see https://github.com/opencog/rocca)  I personally am working on a generic theory of learning, see  https://github.com/opencog/learn and https://github.com/opencog/generate 

If you want a generic chatbot -- well, there are lots of generic chatbots out there. We are not in competition with them. If you want some conversational AI -- there are also lots of systems for that, for game engines (I think there's one or two for Unreal Engine) and then there's GPT3 stuff from OpenAI and Google, and freinds, and there are startups working on chatbots for the medical industry, and the legal industry and insurance ... there's the IBM Watson thing, and Alexa, and Siri.  Effectively all of these are proprietary, and we are not in the business of trying to create an open-source version of Siri or Alexa.  I mean, that could be fun, but there are not enough of us here to do that. ... but also, its not an obvious stepping stone to AGI.  If you want to accuse anyone of a publicity stunt, accuse amazon and google of that. Not us.

**Comment by ngeiswei** [comment]
I don't think anybody is trying to throw insults.

Regarding the state of ocpkg, it is probably lagging behind because core opencog developers tend to go the hard way (I use arch BTW ;-p).  If ocpkg doesn't work, just try to install every component one by one in the proper other, `cogutil`, `atomspace`, etc, cmake is reasonably good at reporting what's missing.  Of course feel free to improve/fix ocpkg if you can/want, that's ultimately welcome.

Regarding using opencog to build a chatbot, I can't help as I've never attempted that (my primary project using opencog these days is rocca https://github.com/opencog/rocca).
