### ISSUE TITLE
nlp-types build error

### ISSUE THREAD

**Issue by alexander-gabriel** [opencog/opencog#3674]
https://github.com/opencog/opencog/blob/759443a250dc9694f4f00ed67c65eedc3d7acce2/opencog/nlp/wsd/CMakeLists.txt#L33
I think this line is supposed to feature 'nlp-oc-types' instead.

**Comment by linas** [comment]
I think you are right. Good catch. fixed in commit 7af3915

FYI, the code there is obsolete. It is still interesting in a theoretical sense; I'm stealing the core concept in order to implement something much more sophisticated (TBD, still a far ways off). But the code there is obsolete.  If you are interested, you should read Mihalcea's original papers on this, and then I can explain in greater detail how it is still an interesting idea (just not quite in it's original form).
