### ISSUE TITLE
REST API in combination with Python shell produces segfault

### ISSUE THREAD

**Issue by cosmoharrigan** [opencog/opencog#535]
Start the REST API: ```restapi.Start```
Enter the Python shell in the cogserver: ```py```
Run this command: ```from opencog.atomspace import *``` and a segfault occurs:
```
[ERROR] Caught signal 11 (Segmentation fault) on thread 139776596203264
	Stack Trace:
	2: ??:0	killpg()
	3: ??:0	PyImport_GetModuleDict()
	4: ??:0	PyImport_AddModule()
	5: ??:0	PyRun_SimpleStringFlags()
	6: PythonEval.cc:291	  opencog::PythonEval::apply_script(std::string const&)
	7: basic_string.h:578	  std::string::operator=(std::string&&)
	8: basic_string.h:288	  std::string::_M_data() const
	9: GenericShell.cc:157	  opencog::GenericShell::eval(std::string const&, opencog::ConsoleSocket*)
	10: ConsoleSocket.cc:232	  opencog::ConsoleSocket::OnLine(std::string const&)
	11: basic_string.h:288	  std::string::_M_data() const
	12: ??:0	thread_proxy()
	13: ??:0	start_thread()
	14: ??:0	__clone()
```

**Comment by inflector** [comment]
This was fixed by: https://github.com/opencog/opencog/pull/1292

**Comment by inflector** [comment]
@cosmoharrigan This bug should be closed after you confirm the above fix. I no longer get this error following the above instructions after the Pull Request #1292.

**Comment by cosmoharrigan** [comment]
@inflector I pulled the latest code, and rebuilt, and got an exception when I tried to reproduce. Please see the session log below.

Shell # 1:
```
$ cd ~/opencog/build
$ ./opencog/server/cogserver
Using default config at lib/opencog.conf
Using default config at ../lib/opencog.conf
link-grammar: Info: Dictionary found at /usr/local/share/link-grammar/en/4.0.dict
Listening on port 17001
```

Shell # 2:
```
rlwrap telnet localhost 17001
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.

opencog> restapi.Start
```

Shell # 1:
```
REST API is now running in a separate daemon thread.
 * Running on http://0.0.0.0:5000/
```

Shell # 2:
```
opencog> py
Entering python shell; use ^D or a single . on a line by itself to exit.

py> 2+2
Connection closed by foreign host.
```

Back to Shell # 1:
```
[2015-02-22 06:09:58:921] [ERROR] Caught signal 11 (Segmentation fault) on thread 140314938431232
	Stack Trace:
	2: ./opencog/server/cogserver (opencog::Logger::Base::~Base() +0x5e) [0x40814e]
	3: ./opencog/server/cogserver (sighand(int) +0xe9) [0x407789]
	4: /lib/x86_64-linux-gnu/libc.so.6 (x +0x36d40) [0x7f9db2922d40]
	5: /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 (x +0x1b92c0) [0x7f9db05302c0]
	6: /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 (x +0x9) [0x7f9db04c1329]
	7: /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 (X +0x22) [0x7f9db0546e02]
	8: /home/cosmo/opencog/build/opencog/cython/libPythonEval.so (opencog::PythonEval::init() +0x51) [0x7f9db200aa71]
	9: /home/cosmo/opencog/build/opencog/cython/libPythonEval.so (opencog::PythonEval::eval_expr(std::string const&) +0x1c) [0x7f9db200b17c]
	10: /home/cosmo/opencog/build/opencog/shell/libscheme-shell.so (opencog::GenericShell::do_eval(std::string const&) +0x3fb) [0x7f9da8da668b]
	11: /home/cosmo/opencog/build/opencog/shell/libscheme-shell.so (opencog::GenericShell::eval(std::string const&, opencog::ConsoleSocket*) +0x30) [0x7f9da8da5fd0]
	12: /home/cosmo/opencog/build/opencog/server/libserver.so (opencog::ConsoleSocket::OnLine(std::string const&) +0x4c) [0x7f9db387467c]
	13: /home/cosmo/opencog/build/opencog/server/libserver.so (opencog::ServerSocket::handle_connection(opencog::ServerSocket*) +0x319) [0x7f9db3871619]
	14: /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.54.0 (( +0xba4a) [0x7f9db2421a4a]
	15: /lib/x86_64-linux-gnu/libpthread.so.0 (( +0x8182) [0x7f9db19b6182]
	16: /lib/x86_64-linux-gnu/libc.so.6 (( +0x6d) [0x7f9db29e700d]

[2015-02-22 06:10:02:000] [INFO] [PythonModule] destructor
Exception KeyError: KeyError(140314938431232,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
```

**Comment by inflector** [comment]
Hmmm, I just pulled down the latest and am getting these new failures.

	 35 - MultiAtomSpaceUTest (SEGFAULT)
	 63 - RuleUTest (OTHER_FAULT)
	 65 - DefaultForwardChainerCBUTest (OTHER_FAULT)
	 85 - AllPythonModuleTests (SEGFAULT)

I wasn't getting any failures before the pull. I'll recheck this issue.

**Comment by inflector** [comment]
Okay, I'm able to repeat this problem, but only intermittently. It worked find the first couple of times I repeated what you did. I'll dig deeper.

**Comment by inflector** [comment]
Looks like the PythonModule code has the same problems that PyEval did. Not grabbing the GIL which crashes when calling Python C API calls are made from a C++ thread.

**Comment by linas** [comment]
My fault, it was late and I merged without fully testing.
#35 is now fixed.
#63 is an old bug that was invisibile: the new code checks for errors and
thus finds a bug.
#65 is fixed
#85 has never passed for me.  crashes in python pln code.

--linas

**Comment by inflector** [comment]
Okay, so this bug appears to be more subtle and difficult than the other bug. I'm following the theory that this relates to the way we are initializing Python when running the CogServer. This bug appears to come from an interaction between Python threads, C threads, and the GIL locking code (or lack thereof), I say this because this bug, bug #535, is crashing because the Python code has a NULL thread object.

When running the python interpreter, the Python initialization happens as a result of a call to `PythonEval::init()` which handles the initialization for the Python interpreter. I had assumed that because the CogServer constructor `CogServer::CogServer()` calls `PythonEval::instance()` which creates a new `PythonEval` object that this meant that `PythonEval::init()` will always be initialized first when the CogServer is created. This assumption was incorrect.

There is also Python initialization in `PythonModule::init()`. When loading a python module like `restapi` this additional initialization for the Python interpreter is invoked. Depending whether or not you already invoked a python prompt using the `cogserver->py` command or not, this init code has different behavior.  From `PythonModule::init()`:

```
    // Start up Python (this init method skips registering signal handlers)
    if (not Py_IsInitialized())
        Py_InitializeEx(0);
    if (not PyEval_ThreadsInitialized()) {
        PyEval_InitThreads();
        // Without this, pyFinalize() crashes
        _mainstate = PyThreadState_Get();
        // Without this, pyshell hangs and does nothing.
        PyEval_ReleaseLock();
```

Note that the above Python initialization is wrapped in `if (not Py_IsInitialized())` and `if (not PyEval_ThreadsInitialized())`. This seems to be a problem for the destructor PythonModule::~PythonModule which contains the following:

```
    // PyFinalize crashes unless we carefully restore stuff...
    PyEval_AcquireLock();
    PyThreadState_Swap(_mainstate);
    PyErr_Clear();
    Py_Finalize();
```

Note that the call to `PyThreadState_Swap(_mainstate)` passes the `_mainstate` thread state variable which will not have been set if the `PyEval_ThreadsInitialized()` call in `PythonModule::init()` returns true, which it will because the threads were already initialized in `PythonEval::init()`. This will likely cause a crash in the destructor for PythonModule if the Python shell is invoked first.

The two separate Python initializations above are needed because `PythonEval::init()` is **not** being called by `PythonEval::instance()` as I had assumed, it is called only when the request handler for the python shell is invoked using `cogserver->py`.  So if you do that before PythonModule is loaded, the init code in PythonModule will not set the `_mainstate` member variable. Since the Python C code doesn't appear to be doing any safety checks internally, this will likely result in a crash in the destructor.

I don't have enough information yet to know exactly what is causing this bug #525 for certain yet, but I am far enough to have a few questions:

1) Are all the requests handled in the CogServer's main thread? It sure looks like these are coming from one thread, i.e. the main CogServer thread, but the presence of a mutex makes me question my understanding. The request queue is a `concurrent_queue` so pushes and pops are thread safe, which raises the question: Why does `CogServer::processRequests` grab a mutex lock?

```
void CogServer::processRequests(void)
{
    std::unique_lock<std::mutex> lock(processRequestsMutex);
    while (0 < getRequestQueueSize()) {
        Request* request = popRequest();
        request->execute();
        delete request;
    }
}
```
2) The `restapi` module does create several different Python threads to listen to incoming REST requests. 

```
    def run(self, args, atomspace):        
        self.atomspace = atomspace
        '''
        make a daemon thread so that it can be interrupted
        '''
        thread = Thread(target=self.invoke)
        thread.setDaemon(True)
        thread.start()
        print "REST API is now running in a separate daemon thread."        

    def invoke(self):
        self.api = RESTAPI(self.atomspace)
        self.api.run(host=IP_ADDRESS, port=PORT)
```

These Python threads are presumably creating Opencog request objects whenever the web server receives a REST api request which get posted to the CogServer request queue, and then processed in the process requests loop in the main CogServer thread. Something like:

```
    CogServer process requests loop
        CogServer process request
            PyRequest execute
                Cython wrapper to restapi handles the request as per registration
```
So it looks like this would still result in requests getting handled in the main CogServer thread. Does the above match your knowledge of this process? Are all requests handled from the main CogServer thread in all cases?

3) It seems to me we would simplify the code and path complexity if we had a single function for initializing all the Python code that gets called in the CogServer constructor. Python, like Scheme, appears to be so tightly integrated into the CogServer and examples which use it, that it no longer ought to be considered an optional module. There are currently two ifdefs in `CogServer::CogServer`

#ifdef HAVE_GUILE
#ifdef HAVE_CYTHON

Are these actually useful? Does anyone ever not define either of these? Will the CogServer run with either of them undefined?

The current approach with initialization happening in either PythonModule or PythonEval, depending on the order that the user types commands in Cogserver is confusing and creates more opportunity for subtle bugs. Is there a reason why a single initialization routine for all Python would be a bad idea?

**Comment by linas** [comment]
Heh.

0) welcome to my world. I tried to fix this a year or two ago, and what you describe is exactly the pain and confusion I went through, whereupon I used vulgar language, said mean things to people and gave up.  You are looking at the code that made me hate python.

1) The cogserver design is wacky. For some half-lame reason, cogserver socket handling (where the requests come from) is done in a different thread than the main cogserver thread.  However, the main cogserver thread must be single-threaded, because some opencog modules are not thread-safe.   So you are right: the mutex in there is almost surely not needed ... I assume its a forgotten left-over from some earlier design, or maybe some voodoo locking, or maybe it actually does something.  However, all requests are supposed to get done in just one thread, and thus should not need locking.

In the future, you should expect to get PyEval to get called from any random thread.

2) you have to ask @cosmo about how REST works.

3)  Currently, cogserver will compile and run if either or both HAVE_GUILE HAVE_CYTHON are not defined. Large parts f embodiment and the space/time servers don't user wither python or guile. Its seems OK to keep the conditional compile for now.   However, you are right -- there does not seem to be much of a point of having a distinct PythonModule -- I think its some tortured attempt to stick to an old design for opencog loadable modules -- a design that appears to be increasingly creaky and irrelevant.   So yes, you can probably nuke PythonModule. Maybe. However ... 

However ... related to all this is a CMakefile crazy-quilt of linking and symbol resolution. Currently, opencog builds, but the dependencies between its different parts are fragile: you can easily discover loops, where e.g. embodiment needs python so it links to it, but cython needs to export  wrappers for embodiment functions and so you get a circular linking mess.  This doesn't happen today, only because cython doesn't wrap embodiment (and because I invented a clever mechanism in guile to explicitly break such linking dependency loops)  I mmention this because if you start getting rid of PythonModule, you might start walking down the circular dependency road, and there is a whole world of hurt on that road.  Been there, done that.

At any rate, I don't know why there are two different init paths for python. I'm guessing its a historical accident, to cover the 4 or 5 different ways that python could get started (as Iron python, as regular python, as a module, from execution links .. whatever.)  Yes, the different init paths should alost surely be merged, but its the testing problem, of getting each of the different usages to all work, that's the hard  part.

**Comment by Cosmo** [comment]
> 2) you have to ask @cosmo about how REST works.

@linas: his name is @cosmoharrigan - please use his name. thanks :)

**Comment by inflector** [comment]
Well, that was fun. Had to fix about six different problems at once to get this to work. And had a crash I couldn't figure out for a few days because the stack trace was useless and I had to resort to brute force analysis.

It turns out you can't actually initialize everything in one place after all. Even though you **need** to initialize Python in **one place**, Cython must be initialized **many places**.

You need to call the Cython-generated import functions:

`import_opencog__atomspace();`

and

`import_opencog__agent_finder();`

in every single shared library that calls a function declared in Cython code as an api. Otherwise, you get a crash on the first call to that function in that shared library. And the SIGSEGV doesn't leave a useful stack trace. It's just two assembly instructions and boom, the register relative callq segfaults. You know it's crashing in the api call, yes, but when you verify that you are indeed calling the import function, hell you just stepped through it, it still crashes. Calling it isn't enough, you need to have called it in that shared library.

And the Cython docs make no mention of this at all (at least until I submit my pull request to fix that).

As an OpenCog newb it is not necessarily obvious which code is running in which shared libraries and where the boundaries lie. It's not real obvious that PythonEval and CogServer and PythonModule are actually in three separate shared libraries until you read through the CMakeLists.txt files enough times.

No wonder you gave up and hate Python.

I've got the test case for this bug working fine now after I sorted out the initialization issues, but I've still got one more problem with CogServerUTest to nail down before I submit the pull request. Turns out the CogServer code doesn't cleanup nicely and CogServer's destructor never gets called because it's a singleton static variable. Since the CogServerUTest fires up more than one instance of a CogServer, it fails in the the safety checks I put in to make sure you don't initialize Python twice are firing. 

However, when you call the destructor for CogServer it crashes with an error in the threading code that is used for the socket listeners for telnet connections. Which might be coming from a real bug so I want to figure out why a clean shutdown isn't working as I have sometimes found clues to fixing really nasty intermittent failures by restoring calls to destructors when they weren't getting called before like this in case. Sometimes the expedient assumption that "who cares about destructors when the application is quitting anyway" just masks real problems.

**Comment by linas** [comment]
There is no requirement that it must be possible to start a cogserver, shut it down, and start it again, and have things work.  So splitting CogServerUTest into two tests is an acceptable solution.

The socket code is wonky; I have the impression that whoever wrote it did not understand tcp/ip.  Its over-complexticated.

There's lots and lots of code that prevents double initialization by saying `static bool init=false; if (init) return; init=true;` it mostly works just fine except in one case where multiple threads hit it at the exact same time.

**Comment by inflector** [comment]
There were quite a few other places, including the `atomspace_bm` benchmark and a few other unit tests which were also running more than one CogServer instantiation, mostly through stack-based CogServer objects. So I decided to make sure that the Python code, could be initialized and finalized reliably over and over again. I found four or five new and different problems in the process. So now CogServer's destructor works reliably and you can start and stop as many as you want in testing.

I also found out about some really dumb inconsistencies in the Python C API. It turns out that a few, but not many, of the Python C API calls return what they call a "borrowed reference" which means that the object is returned without first incrementing the reference count. So the object reference returned by the C API call can refer to an object that will potentially go away at any time you make another Python API call. We were using some of these in some cases in ways that were unsafe. In other cases, we were decrementing the reference count on API-returned `PyObject*` pointers when we shouldn't have, which would cause the object reference count to drop to zero either then or at some other point in the future inside the Python system, and this would cause a crash when Python itself needed them since it didn't know you had decremented the reference count for one of its objects. At the very least, this would cause a crash in `Py_Finalize()`;

Dumb of the Python api keepers (Guido?) to have this inconsistency. Given the huge overhead of each of the API calls, one more decrement isn't going to be noticed. It just makes concepts which are already fairly complex and tricky even worse. And the documentation only intermittently mentions these "borrowed references" sometimes it says it by the API call, and other times it only does for certain versions of the docs. In many cases, you'll have three API calls in a row where it tells you either "borrowed reference" or "new reference" and then one or two where it doesnt tell you which it is. And if you Google a particular API call, you might find it tells you, or not, depending on which version of the docs it brings up. Consistently returning strong references would have been the much wiser call and keep you from having to look them all up one by one to know what to do.

So I added a bunch of extra tests and created a new unit test for repeated initialization and finalization of various parts of PythonEval so we can surface problems like this more quickly if they are introduced in the future.

**Comment by inflector** [comment]
@cosmoharrigan Pull request #1325 has been merged. Please close this once you can confirm the fix.

**Comment by cosmoharrigan** [comment]
@inflector The test case described before in https://github.com/opencog/opencog/issues/535#issuecomment-75422008 works now on my machine.

However, I'm not able to add a node to the atomspace in the Python shell inside the CogServer without getting a Segmentation fault. But that's not within the scope of this particular GitHub issue, so I'll close this now.
